### ISSUE TITLE
can't ctx.scene.enter when leaving a scene

### ISSUE THREAD

**Issue by belotserkovtsev** [telegraf/telegraf#1029]
i can't get how to enter a new scene when you're leaving one. not sure if it's a bug or i just don't know how to do it correctly but there's my code:

```js
nickname.leave(ctx => {
    if(ctx.session.isLoggedIn || (fs.existsSync('./userdata/' + ctx.message.from.username + '.json') && JSON.parse(fs.readFileSync('./userdata/' + ctx.message.from.username + '.json')).loggedIn))
        ctx.scene.enter('menuLoggedIn');
    else
        ctx.scene.enter('menu');
});
```

the error i get:
<details>

#### 

```
Exception in PromiseRejectCallback:
/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:373
          return Promise.reject(err)
                         ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/scenes/context.js:75
    return handler(this.ctx, noop).then(() => this.reset())
                                   ^

RangeError: Maximum call stack size exceeded
102:ig bmb$ node index.js 
Exception in PromiseRejectCallback:
/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:373
          return Promise.reject(err)
                         ^

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/scenes/context.js:75
    return handler(this.ctx, noop).then(() => this.reset())
                                   ^

RangeError: Maximum call stack size exceeded
(node:17100) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at SceneContext.get session [as session] (/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/scenes/context.js:14:15)
    at SceneContext.get current [as current] (/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/scenes/context.js:34:26)
    at SceneContext.leave (/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/scenes/context.js:72:26)
    at SceneContext.enter (/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/scenes/context.js:47:42)
    at /Users/bmb/Documents/nodejs/ig/index.js:135:15
    at execute (/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:370:13)
    at /Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:370:49
    at /Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:135:56
    at execute (/Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:370:13)
    at /Users/bmb/Documents/nodejs/ig/node_modules/telegraf/composer.js:355:14
(node:17100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
</details>

**Comment by belotserkovtsev** [comment]
as i understand .enter function calls .leave if you are in a scene already, so that's why there's a 'Maximum call stack size exceeded'. i undersatnd that i can just .enter a scene then instead of .leave, but it still

**Comment by MikeMajara** [comment]
Are you able to just leave one?

**Comment by KnorpelSenf** [comment]
Closing because of inactivity.
