### ISSUE TITLE
429: Too Many Requests: retry after 18053 only on telegram.sendContact

### ISSUE THREAD

**Issue by valeryi** [telegraf/telegraf#1046]
## Context

* Telegraf.js Version: "telegraf": "^3.38.0",
* Node.js Version: "12.16.3"
* Operating System: Windows 7 64

## Expected Behavior

I've got an issue with Too many requests only when I try to send a contact via telegram.sendContact. But when I am sending a message via telegram.sendMessage everything is fine.

I think I may have done some loop somewhere haven't close requests or something which are still pending or something or it's an issue with the framework. 

I already tried to put `ctx.answerCb` everywhere where I 've found but it did not help.

**EDIT:** 
I already tried to start a new project with only this line and I get the error anyway. 
There must be some updates or something that caused that weird behaviour because before it seemed to work fine for me. I didn't notice any issues with Contacts 

```
bot.hears(
    /(Contacts)|(Контакты)|(Контакти)/i,
    //@ts-ignore
    getUserInfo,
    updateUserActivity,
    async (ctx: ITelegramContext) => {
      // @ts-ignore
      ctx.telegram.sendContact(
        //@ts-ignore
        **********,
        +***********,
        "name"
      )
    }
  );
```
### Failure Logs
```
(node:8620) UnhandledPromiseRejectionWarning: Error: 429: Too Many Requests: retry after 17496
    at C:\Users\Валерий\Documents\Projects\TelegramBOT\node_modules\telegraf\core\network\client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Piterden** [comment]
Maybe sent contact matches your expression and causes a recursion?

**Comment by valeryi** [comment]
Just checked it twice right now. I already thought it was the issue but no. There's some other problem. Thanks for such a soon response!

**Comment by max-java** [comment]
Hello, got the same issue using java:
429: Too Many Requests: retry after **** only on sendContact 

did you figure out what was the root cause?

**Comment by valeryi** [comment]
> Hello, got the same issue using java:
> 
> 429: Too Many Requests: retry after **** only on sendContact 
> 
> 
> 
> did you figure out what was the root cause?

Hey! No, unfortunately I didn’t fix that issue in Telegraf.

**Comment by KnorpelSenf** [comment]
If possible, please provide a [SSCCE](http://sscce.org/). Otherwise, please handle the rejection of the promise and share a stacktrace.

**Comment by KnorpelSenf** [comment]
Closing because of inactivity. Please reopen if this is still an issue.

May be fixed by #1205.

**Comment by BhavyaLight** [comment]
Facing this exact issue at the moment

**Comment by KnorpelSenf** [comment]
1. What version of telegraf are you using?
2. Can you share a stacktrace of the error?

**Comment by BhavyaLight** [comment]
Thanks!  I suspect it is an issue from telegram and not this library. Here, however is the info in case this helps :

my code:

```bot.on('text', (ctx) => {
  // Explicit usage
  ctx.telegram.sendContact(ctx.message.chat.id, '74738743874', 'Names');

  // Using context shortcut
  ctx.reply(`Hello ${ctx.state.role}`);
});
````

1)  telegraf"  v4.3.0
2)
```
(node:19804) UnhandledPromiseRejectionWarning: Error: 429: Too Many Requests: retry after 6470
    at Telegram.callApi (C:....\backend\node_modules\telegraf\lib\core\network\client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:19804) Error: 429: Too Many Requests: retry after 6470
    at Telegram.callApi (C:....\backend\node_modules\telegraf\lib\core\network\client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:19804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will 
terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:19804) UnhandledPromiseRejectionWarning: Error: 429: Too Many Requests: retry after 6470
    at Telegram.callApi (C:....\backend\node_modules\telegraf\lib\core\network\client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:19804) Error: 429: Too Many Requests: retry after 6470
    at Telegram.callApi (C:....\backend\node_modules\telegraf\lib\core\network\client.js:258:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

**Comment by KnorpelSenf** [comment]
Thanks for the additional info. It does indeed seem like an error on the Telegram side, especially given that you're supposed to retry after 6470 seconds (that's roughly 1 h 47 min). I don't think this is caused by telegraf.

You may want to open an issue in this repo instead: https://github.com/tdlib/telegram-bot-api

Note that you should use `async` middleware and `await` the API calls to make sure you can catch errors like that with you bot's error handler :wink:
```ts
  await ctx.reply(`Hello ${ctx.state.role}`);
```

**Comment by NormandoHall** [comment]
In Telegram Bot Talk

![image](https://user-images.githubusercontent.com/2943127/133723695-74bccd1d-71b6-4ec1-9a11-53c7bca87764.png)

https://t.me/BotTalk

**Comment by KnorpelSenf** [comment]
https://t.me/BotTalk/267907 is probably interesting to you, @KnightNiwrem
