### ISSUE TITLE
Example on Openshift webhook

### ISSUE THREAD

**Issue by rizaumami** [telegraf/telegraf#109]
@dotcypress, could you please give us an example on how to deployed a telegraf based bot on Openshift with webhook?

Thanx

**Comment by dotcypress** [comment]
Hey.

Try following example. You need to set `BOT_TOKEN` env variable before starting.

```js
const Telegraf = require('Telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)
bot.on('text', ({ reply }) => reply('Hey from OpenShift!'))

const secret = Math.random().toString(36).slice(2)
bot.telegram.setWebhook(`https://${process.env.OPENSHIFT_APP_DNS}/${secret}`)
bot.startWebhook(`/${secret}`, process.env.OPENSHIFT_NODEJS_IP, process.env.OPENSHIFT_NODEJS_PORT)
```

**Comment by rizaumami** [comment]
```
https.js:17
    opts.NPNProtocols = ['http/1.1', 'http/1.0'];
                      ^

TypeError: Cannot create property 'NPNProtocols' on string '127.4.84.1'
    at new Server (https.js:17:23)
    at Object.createServer (https.js:48:10)
    at Telegraf.startWebhook (/var/lib/openshift/591fe70789f5cfa65100003f/app-root/runtime/repo/node_modules/telegraf/lib/telegraf.js:75:26)
    at Object.<anonymous> (/var/lib/openshift/591fe70789f5cfa65100003f/app-root/runtime/repo/bot.js:8:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

**Comment by dotcypress** [comment]
Sorry, typo in example 😊
Replace last line with following:
```js
bot.startWebhook(`/${secret}`, null, process.env.OPENSHIFT_NODEJS_IP, process.env.OPENSHIFT_NODEJS_PORT)
```

**Comment by rizaumami** [comment]
Error message above is gone, but I never received `Hey from OpenShift!` message.
And there is now new error:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.4.84.1
```
FYI, I've modified the example script like this is it won't set webhook everytime it's started (I've manually set the secret address to /botTOKEN):
```js
const Telegraf = require('telegraf')
const BOT_TOKEN = 'xxx:xxxxxxxxxxxxxxxxxxxx'
const bot = new Telegraf(BOT_TOKEN)
bot.on('text', ({ reply }) => reply('Hey from OpenShift!'))

bot.startWebhook(`/bot${BOT_TOKEN}`, null, process.env.OPENSHIFT_NODEJS_IP, process.env.OPENSHIFT_NODEJS_PORT)
```

**Comment by dotcypress** [comment]
@rizaumami could you provide steps you using for deploy?

**Comment by rizaumami** [comment]
Just a regular `git add .` -> `git commit -m 'message'` -> `git push`, then `rhc ssh GEAR` to manually start the script

**Comment by dotcypress** [comment]
@rizaumami do you see any errors in logs? 

And you might try to get some details by calling `getWebhookInfo` method:
 `curl https://api.telegram.org/bot${BOT_TOKEN}/getWebhookInfo`

**Comment by rizaumami** [comment]
```json
{
  "ok": true,
  "result": {
    "url": "https://xxxxxx-xxxxx.rhcloud.com/botxxxxx:xxxxxxx",
    "has_custom_certificate": false,
    "pending_update_count": 3,
    "last_error_date": 1495365483,
    "last_error_message": "Wrong response from the webhook: 503 Service Temporarily Unavailable",
    "max_connections": 40
  }
}
```

**Comment by dotcypress** [comment]
Seems like you webhook isn't working properly, try `curl https://xxxxxx-xxxxx.rhcloud.com/botxxxxx:xxxxxxx`

**Comment by rizaumami** [comment]
Here is the results: `curl: (5) Could not resolve proxy: POST`

@dotcypress, thank you for your help. I know nothing about networking/openshif, so I accept this issue as unresolved and you're free to close it.

**Comment by rizaumami** [comment]
Jus a follow up so others can benefit from this.

@dotcypress, it seems that you gave me wrong example for `startWebhook`. 
According to https://github.com/telegraf/telegraf/blob/develop/lib/telegraf.js#L69, it's:
```js
bot.startWebhook(path, null, process.env.OPENSHIFT_NODEJS_PORT, process.env.OPENSHIFT_NODEJS_IP)
```
Not:
```js
bot.startWebhook(path, null, process.env.OPENSHIFT_NODEJS_IP, process.env.OPENSHIFT_NODEJS_PORT)
```
So, I edit the script accordingly:
```js
const Telegraf = require('telegraf')

const TOKEN = 'TOKEN_HERE'
const bot = new Telegraf(TOKEN)
bot.on('text', ({ reply }) => reply('Hey from OpenShift!'))

bot.startWebhook(`/bot${TOKEN}`, null, process.env.OPENSHIFT_NODEJS_PORT, process.env.OPENSHIFT_NODEJS_IP)
```
And manually set webhook using `curl`:
```sh
curl 'https://api.telegram.org/botTOKEN/setWebhook?url=xxxxxx-xxxxxx.rhcloud.com:443/botTOKEN'
```
Now, the bot responds to messages. But, `getWebhookInfo` indicating something wrong:
```sh
{
  "ok": true,
  "result": {
    "url": "xxxxx-xxxxx.rhcloud.com:443/botTOKEN",
    "has_custom_certificate": false,
    "pending_update_count": 0,
    "last_error_date": 1499005189,
    "last_error_message": "Wrong response from the webhook: 503 Service Temporarily Unavailable",
    "max_connections": 40
  }
}
```
And here is the `curl -d` output:
```html
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.0</center>
</body>
</html>
```
