### ISSUE TITLE
Fastify example not working

### ISSUE THREAD

**Issue by lifehome** [telegraf/telegraf#1092]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: v10.21.0
* Operating System: macOS 10.15.6

## Expected Behavior
It should work as described

## Current Behavior
It has output an error:
```
/Users/lifehome/workspace/SilentServiceBot/node_modules/fastify/fastify.js:395
    throw new FST_ERR_MISSING_MIDDLEWARE()
    ^
FastifyError: You must register a plugin for handling middlewares, visit fastify.io/docs/latest/Middleware/ for more info.
    at Object.use (/Users/lifehome/workspace/SilentServiceBot/node_modules/fastify/fastify.js:395:11)
    at Object.<anonymous> (/Users/lifehome/workspace/SilentServiceBot/server.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

## Failure Information (for bugs)

Shown as above

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Copy the fastify example code to IDE, install dependencies.
2. Run it
3. You get the error.
### Failure Logs

Shown as above.

**Comment by KnorpelSenf** [comment]
Please check out the new example bot for fastify that was introduced in #1168, maybe that can help you.

**Comment by erfanium** [comment]
@lifehome 
As @KnorpelSenf  said, you should register this plugin for `fastify`: https://www.npmjs.com/package/fastify-telegraf

@KnorpelSenf When will the site document be updated? Because this breaked example still exists on the site

**Comment by KnorpelSenf** [comment]
> When will the site document be updated?

No idea. There's the plan to move to `typedoc` (cf. #1074), but I'm not sure whether there's more work that needs to be done about this. Also, I have no access to the website

**Comment by wojpawlik** [comment]
Website will update itself on release. Typedoc docs are ready and waiting since November 13 for @dotcypress to host them on Vercel.
