### ISSUE TITLE
getting error while starting bot

### ISSUE THREAD

**Issue by vineelsai26** [telegraf/telegraf#1127]
``` Launch failed
Error: 404: Not Found
    at /home/codespace/workspace/F.R.I.D.A.Y-Bot/node_modules/telegraf/core/network/client.js:281:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) ```

getting this error while starting the bot everything worked fine until some time but suddenly getting this error if I deploy to Heroku everything is working fine here is my code https://github.com/vineelsai26/F.R.I.D.A.Y-Bot

**Comment by imdkbj** [comment]
Just run ur bot on polling and didn't found any issue.

**Comment by KnorpelSenf** [comment]
I assume that your issue is fixed. It does not look like an issue with `telegraf` to me. It could be something with your deployment on Heroku.
