### ISSUE TITLE
TypeError [ERR_INVALID_PROTOCOL] [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by septs** [telegraf/telegraf#1183]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: Node.js 12
* Operating System: AWS Lambda

## Expected Behavior

Correctly handle `http` and `https` media url.

check url schema use different agent.

## Current Behavior

```
TypeError [ERR_INVALID_PROTOCOL] [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
```

## Failure Information (for bugs)

```
TypeError [ERR_INVALID_PROTOCOL] [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
      at new ClientRequest (_http_client.js:152:11)
      at request (http.js:46:10)
      at abortAndFinalize (/var/webpack:/@nice-labs/personal-bot/node_modules/node-fetch/lib/index.js:1432:1)
      at new Promise (<anonymous>)
      at Promise (/var/webpack:/@nice-labs/personal-bot/node_modules/node-fetch/lib/index.js:1404:1)
      at id (/var/webpack:/@nice-labs/personal-bot/node_modules/telegraf/core/network/client.js:159:1)
      at media (/var/webpack:/@nice-labs/personal-bot/node_modules/telegraf/core/network/client.js:151:1)
      at /var/webpack:/@nice-labs/personal-bot/node_modules/telegraf/core/network/client.js:98:1
      at Array.map (<anonymous>)
      at MultipartStream (/var/webpack:/@nice-labs/personal-bot/node_modules/telegraf/core/network/client.js:97:1)
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `await ctx.replyWithPhoto({ url: "http://example.com", filename: 'unknown.jpg' });`
2. throw type error

### Failure Logs

Please include any relevant log snippets or files here.

----------

Related code:

https://github.com/telegraf/telegraf/blob/fc5882cd52505aa81b7d0f8620838b9a6b4dad40/src/core/network/client.ts#L53-L56
https://github.com/telegraf/telegraf/blob/fc5882cd52505aa81b7d0f8620838b9a6b4dad40/src/core/network/client.ts#L203-L213

**Comment by KnorpelSenf** [comment]
Related to #814
