### ISSUE TITLE
Error in the inline-bot.js example

### ISSUE THREAD

**Issue by ajsb85** [telegraf/telegraf#120]
```console
async function spotifySearch (query = '', offset, limit) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by dotcypress** [comment]
Node 7.x with `async/await` support is required for running this example.
