### ISSUE TITLE
Unsupported message type

### ISSUE THREAD

**Issue by ajsb85** [telegraf/telegraf#131]
This error appears when I add or remove the bot to a group.

```console
Error: Unsupported message type
    at Telegram.sendCopy (/node_modules/telegraf/lib/telegram.js:250:13)
    at bot.on (/src/node_0ebb475d25599.tmp:58:41)
    at Promise.resolve.then (/node_modules/telegraf/lib/core/composer.js:63:56)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by dotcypress** [comment]
@ajsb85  `sendCopy` supports only following updates:
```
audio
contact
document
location
photo
sticker
text
venue
video
video_note
voice
```

**Comment by ajsb85** [comment]
Thanks!
