### ISSUE TITLE
Examples are not working.

### ISSUE THREAD

**Issue by el-lsan** [telegraf/telegraf#1314]
## Context

* Telegraf.js Version: 4.0.1
* Node.js Version: ^15.0.1
* Operating System: Mac OS 10.15.6

## Minimal Example Code Reproducing the Issue

```ts
const { Telegraf, Markup } = require('telegraf')
const config = require('./config/config')
const token = config.API_TOKE;
if (token === undefined) {
  throw new Error('BOT_TOKEN must be provided!')
}

const bot = new Telegraf(token)

bot.use(Telegraf.log())

bot.command('custom', ({ reply }) => {
  return reply('Custom buttons keyboard', Markup
    .keyboard([
      ['🔍 Search', '😎 Popular'], // Row1 with 2 buttons
      ['☸ Setting', '📞 Feedback'], // Row2 with 2 buttons
      ['📢 Ads', '⭐️ Rate us', '👥 Share'] // Row3 with 3 buttons
    ])
    .oneTime()
    .resize()
  )
})

bot.hears('🔍 Search', ctx => ctx.reply('Yay!'))
bot.hears('📢 Ads', ctx => ctx.reply('Free hugs. Call now!'))

bot.command('special', (ctx) => {
  return ctx.reply(
    'Special buttons keyboard',
    Markup.keyboard([
      Markup.button.contactRequest('Send contact'),
      Markup.button.locationRequest('Send location')
    ]).resize()
  )
})

bot.command('pyramid', (ctx) => {
  return ctx.reply(
    'Keyboard wrap',
    Markup.keyboard(['one', 'two', 'three', 'four', 'five', 'six'], {
      wrap: (btn, index, currentRow) => currentRow.length >= (index + 1) / 2
    })
  )
})

bot.action(/.+/, (ctx) => {
  return ctx.answerCbQuery(`Oh, ${ctx.match[0]}! Great choice`)
})

bot.launch()

```

## Expected Behavior
 Not crashing, working example

## Current Behavior
The bot is crashing 

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
/Users/ehsan/Documents/testing/node_modules/telegraf/lib/context.js:211
        this.assert(this.chat, 'reply');
             ^

TypeError: Cannot read property 'assert' of undefined
    at reply (/Users/ehsan/Documents/testing/node_modules/telegraf/lib/context.js:211:14)
    at /Users/ehsan/Documents/testing/index.js:13:10
    at /Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:157:111
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async execute (/Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:456:17)
    at async /Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:457:21
    at async execute (/Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:456:17)
    at async /Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:457:21
    at async execute (/Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:456:17)
    at async /Users/ehsan/Documents/testing/node_modules/telegraf/lib/composer.js:457:21


```

**Comment by vaaski** [comment]
> ```diff
> -  bot.on('connected_website', ({ reply }) => reply('Website connected'))
> +  bot.on('connected_website', (ctx) => ctx.reply('Website connected'))
> ```

why does destructuring not work in this case?

**Comment by wojpawlik** [comment]
#1253
