### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED] Package subpath './lib/core/network/error' is not defined by "exports"

### ISSUE THREAD

**Issue by esindger** [telegraf/telegraf#1324]
It's unable to import `TelegramError` class due to the next error:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/core/network/error' is not defined by "exports" in <project_path>/node_modules/telegraf/package.json
    at applyExports (internal/modules/cjs/loader.js:498:9)
    at resolveExports (internal/modules/cjs/loader.js:514:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (<project_path>/dist/helpers/ctx.js:8:33)
```
## Context

* Telegraf.js Version: 4.0.1
* Node.js Version: 14
* Operating System: macOS

## Minimal Example Code Reproducing the Issue

```ts
import TelegramError from 'telegraf/lib/core/network/error'

try {
    ctx.telegram.getChatAdministrators(chatId)
} catch(e) {
  if (error instanceof TelegramError &&
    // handle telegram error
  } else {
    // handle other errors
  }
}
```

## Expected Behavior

Ability to import `TelegramError`.

**Comment by Autapomorph** [comment]
See #1289
