### ISSUE TITLE
429: Too Many Requests: retry after 73414

### ISSUE THREAD

**Issue by valeryi** [telegraf/telegraf#1390]
## Context

* Telegraf.js Version: ^4.0.0
* Node.js Version: v14.16.0
* Operating System: MacOS Catalina 10.15.7

## Minimal Example Code Reproducing the Issue

```ts
async function handler(ctx: TelegramContext) {

    try {

        await ctx.deleteMessage();

        const chat_id = ctx.message?.chat.id as number;
    
        await ctx.telegram.sendContact(chat_id, '+3806777777777', 'name', {
            'last_name': ''
        })
        await ctx.reply('Director');
    
        await ctx.telegram.sendContact(chat_id, '+380633333333', 'name', {
            'last_name': ''
        })
        await ctx.reply('Director');
        await ctx.reply('Нас можно найти за адресом:');
        await ctx.reply('ул. Крещатик 1');

    } 
    catch(err) {
        console.log(err.message);
    }

}

export default function handlerContacts(bot: Telegraf<TelegramContext>) {
    bot.hears(/(Контакти)/, handler);
}
```

At first, it worked fine and I could get contact cards. But after some time code with contacts doesn't work and throws an error: 429: Too Many Requests: retry after 73414

## Expected Behavior

I should see Contact Cards and app shouldn't crash.

## Current Behavior

Code doesn't work. 
Everything what is after 

```ts
        await ctx.telegram.sendContact(chat_id, '5346464636', 'name', {
            'last_name': 'last_name'
        })
```

doesn't work

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
(node:41) UnhandledPromiseRejectionWarning: Error: 429: Too Many Requests: retry after 74300
2021-03-07T21:20:42.433883+00:00 app[web.1]:     at Telegram.callApi (/app/node_modules/telegraf/lib/core/network/client.js:258:19)
2021-03-07T21:20:42.433884+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-03-07T21:20:42.434017+00:00 app[web.1]: (node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

**Comment by 2naive** [comment]
Same: https://github.com/telegraf/telegraf/issues/1207#issuecomment-784733204

What are the best practices or implementation plans?

**Comment by iamgabrielsoft** [comment]
Have you tried using a middleware, it could be resolved

**Comment by ivorsmorenburg** [comment]
This a shame that it doesn't handle rate limit automatically out of the box. Feels the best solution will be to use a normal HTTP request and handle everything yourself. Whats the point in using a library that I have to control how many requests..
