### ISSUE TITLE
Wizard error because session () is deprecated

### ISSUE THREAD

**Issue by NelsonHernandezM** [telegraf/telegraf#1457]
## Context

* Telegraf.js Version: 4.3.0
* Node.js Version: 16.1.0
* Operating System: Windows

## Minimal Example Code Reproducing the Issue

```ts
const wizardScene = new Scenes.WizardScene(
    'first-scene',
    async (ctx) => {
      await ctx.reply('whats your name');
      return ctx.wizard.next();
    },
    async (ctx) => {
      ctx.wizard.state.name = ctx.message.text;
      await ctx.reply('age ?');
      return ctx.wizard.next();
    },
    async (ctx) => {
      ctx.wizard.state.age = ctx.message.text;
      await ctx.reply(
        `Your name is ${ctx.wizard.state.name} and age is ${ctx.wizard.state.age}`
      );
      await ctx.reply('exiting scene');
      return ctx.scene.leave();
    }
  );
  
  const stage = new Scenes.Stage([wizardScene]);
  
  bot.use(stage.middleware());
  bot.use(session());
```

## Expected Behavior
I saw this "solution" but honestly I did not understand it,
To do so:

Initialize session like this:
‘’ ’
session ({
property: 'chatSession',
getSessionKey: (ctx) => ctx.chat && ctx.chat.id,
})
‘’ ’

pass {sessionName: 'chatSession'} in Stage constructor 

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
(node:5840) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'enter' of undefined
    at D:\RESSS\botPruebas.js:22:15
    at D:\RESSS\node_modules\telegraf\lib\composer.js:158:111
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async execute (D:\RESSS\node_modules\telegraf\lib\composer.js:458:17)
    at async D:\RESSS\node_modules\telegraf\lib\composer.js:459:21
    at async execute (D:\RESSS\node_modules\telegraf\lib\composer.js:458:17)
    at async D:\RESSS\node_modules\telegraf\lib\composer.js:459:21
    at async execute (D:\RESSS\node_modules\telegraf\lib\composer.js:458:17)
    at async D:\RESSS\node_modules\telegraf\lib\composer.js:459:21
    at async execute (D:\RESSS\node_modules\telegraf\lib\composer.js:458:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will 
terminate the Node.js process with a non-zero exit code.
```

**Comment by ph98** [comment]
Same Problem with Scene did someone have a solution ?

**Comment by FeiFanLiang** [comment]
me too,Hope to provide the latest examples

**Comment by metehus** [comment]
Try to start the session first

```js
  bot.use(session());
  bot.use(stage.middleware());
```
