### ISSUE TITLE
sendMessage failed, reason: socket hang up

### ISSUE THREAD

**Issue by damozhang** [telegraf/telegraf#1559]
## Error logs
```
/ProjectPath/node_modules/node-fetch/lib/index.js:1483
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
          ^
FetchError: request to https://api.telegram.org/[BOT_TOKEN]:[REDACTED]/sendMessage failed, reason: socket hang up
    at ClientRequest.<anonymous> (//ProjectPath/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (node:events:390:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:402:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

* Telegraf.js Version: 4.5.2
* Node.js Version: 16.13.0
* Operating System: macOS 12.1

## Minimal Example Code Reproducing the Issue

```ts
const bot: Telegraf<Context<Update>> = new Telegraf(config.telegramBotToken);
bot.use(async (ctx, next) => {
  if (ctx.from && config.allowedUsers.includes(ctx.from.id.toString())) {
    await next();
  } else {
    ctx.reply("Sorry, you are not allowed to use this bot.");
  }
});

bot.use(async (_, next) => {
  const start = dayjs();
  await next();
  const ms = dayjs().diff(start);
  console.log("Response time: %sms", ms);
});

bot.launch();

cron.schedule("*/15 * * * *", async () => {
  const msg = `-= Heartbeat ${dayjs.utc().format("HH:mm")} UTC =-`;
  try {
    bot.telegram.sendMessage(config.telegramChatId, msg);
  } catch (error) {
    console.log("schedule error:", error);
  }
});

process.once("SIGINT", () => {
  bot.stop("SIGINT");
});
process.once("SIGTERM", () => {
  bot.stop("SIGTERM");
});
```

This error will be thrown  after running for a period of time

**Comment by Levelleor** [comment]
Have you found a solution to this? Is there a way to safely reestablish connection?

**Comment by Mikiyas721** [comment]
I am facing similar error, but with answer answerCallBackQuery
FetchError: request to https://api.telegram.org/botBOT_TOKEN:[REDACTED]/answerCallbackQuery failed, reason: socket hang up

**Comment by damozhang** [comment]
> Have you found a solution to this? Is there a way to safely reestablish connection?

No, I haven't.

**Comment by b10c77** [comment]
I'm facing a similar issue as well and can't see to be able to trap the error and manage it (add the message to a queue for example and try to re-submit).

```
XXX\node_modules\node-fetch\lib\index.js:1491
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://api.telegram.org/XXX:[REDACTED]/sendMessage failed, reason: connect ETIMEDOUT 149.154.167.220:443
    at ClientRequest.<anonymous> (XXX\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

**Comment by turdiyev** [comment]
Who find solution for this error?

**Comment by cryptozoidberg** [comment]
Any success with handling this problem?

**Comment by Levelleor** [comment]
I ended up creating new clients for bot each time I am doing a request just to make sure each run is as independent as possible. Doesn't look like the single instance can recover after a connection loss.

**Comment by estoylive** [comment]
i am having the same error but with getMe

FetchError: request to https://api.telegram.org/bot5557498636:[REDACTED]/getMe failed, reason: read ECONNRESET

**Comment by ricardoamedeiros** [comment]
I resolved creating a new connection a each new request without to use keepAlive:

```javascript
TelegrafModule.forRootAsync({
      useFactory: async (configService: ConfigService) => ({
        token: configService.get('TELEGRAM_BOT_TOKEN'),
        options: {
          telegram: {
            agent: new https.Agent({
              keepAlive: false,
            }),
          }
        },
```

**Comment by Muzaffar-Shoshiy** [comment]
I have solution: just require("http"); require("https")

**Comment by mtvspec** [comment]
In my case this issue is present if no internet connection is available. Is there any solution to catch connection error and try to reconnect when internet connection is back? Now in this case the server is completely shuts down.

**Comment by jerrychong25** [comment]
> I have solution: just require("http"); require("https")

Hi @Muzaffar-Shoshiy ,

Mind to share full working code?

Thanks in advance.

**Comment by pierluigizagaria** [comment]
there's no solution? this is getting me crazy, happens suddenly anc cant't catch the error. the whole process restarts

**Comment by RileyCodes** [comment]
Can confirm this issue still exists in telegraf@4.12.2

**Comment by MKRhere** [comment]
This is a network issue; not something Telegraf can solve.

Since more users always ask this question, and find themselves in this issue, I'm going to answer this as comprehensively as I can, one last time:

### Catching errors in API calls

If you'd like to catch these errors, use `bot.catch`.

```TS
bot.catch(error => {
	// handle error
});
```

For this to work, you must await all API calls, such as `await ctx.sendMessage(...)`.

### Catching polling errors

However, if the error happens when polling, it will crash the bot. You can catch polling errors by catching `await bot.launch()`, however it will not restart the bot. You'll need to call `bot.launch()` again. Rather, the best way forward would be to *not* catch polling errors, and allow the bot to crash, so it can be cleanly restarted with systemd, or pm2.

### Disabling keep-alive

If you'd like to disable keep-alive, you can try:

```TS
import { Agent } from "node:https";

const bot = new Telegraf(token, {
	telegram: {
		agent: new Agent({ keepAlive: false }),
	},
});
```

There's nothing more Telegraf, or any library can do for you. Sorry. You might have better luck with another network or VPN.
