### ISSUE TITLE
tg.telegram.setMyCommands isn't work

### ISSUE THREAD

**Issue by maksim10411072** [telegraf/telegraf#1589]
when i try to create list of commands, i get error:
```
Uncaught TelegramError Error: 400: Bad Request: BOT_COMMAND_INVALID
    at TelegramError ([c:\Users\Maxim\node_modules\telegraf\lib\core\network\error.js:6:9]())
    at callApi ([c:\Users\Maxim\node_modules\telegraf\lib\core\network\client.js:264:19]())
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
my code:
```
tg.telegram.setMyCommands([
  {command: "/Перевод", description:"[сумма] [айди человека которому отправляете] - переводит сумму человеку"},
  {command: "/Баланс", description:"отображает ваш баланс"}
])
```

Telegraph.js 4.7.0
Node.js v16.14.0.
Windows 10

**Comment by hypernova7** [comment]
Don't use slashes in the command field

Try this way
```javascript
tg.telegram.setMyCommands([
  {command: "Перевод", description:"[сумма] [айди человека которому отправляете] - переводит сумму человеку"},
  {command: "Баланс", description:"отображает ваш баланс"}
])
```

**Comment by Malagor** [comment]
Use Latin letters and lowercase for commands. Also, the command should not start with a "/"
```
tg.telegram.setMyCommands([
  {command: "transfer", description:"[сумма] [айди человека которому отправляете] - переводит сумму человеку"},
  {command: "balanсe", description:"отображает ваш баланс"}
])
```
