### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by YZvirblis** [telegraf/telegraf#1679]
App crashes on heroku.

After I deploy the app to heroku it works for approximately half an hour and crashes.
I couldn't find anything on the issue or relevant to it.

log from heroku:

```
2022-08-26T16:05:49.798641+00:00 app[web.1]:     at execute (/app/node_modules/telegraf/lib/composer.js:468:23)
2022-08-26T16:05:49.798641+00:00 app[web.1]:     at /app/node_modules/telegraf/lib/composer.js:469:27
2022-08-26T16:05:49.798641+00:00 app[web.1]:     at /app/node_modules/telegraf/lib/composer.js:157:31
2022-08-26T16:05:49.798642+00:00 app[web.1]:     at /app/node_modules/telegraf/lib/composer.js:163:111
2022-08-26T16:05:49.798642+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-26T16:05:49.798642+00:00 app[web.1]:     at async execute (/app/node_modules/telegraf/lib/composer.js:468:17)
2022-08-26T16:05:49.798642+00:00 app[web.1]:     at async /app/node_modules/telegraf/lib/composer.js:469:21
2022-08-26T16:05:49.798643+00:00 app[web.1]:     at async execute (/app/node_modules/telegraf/lib/composer.js:468:17)
2022-08-26T16:05:49.962326+00:00 heroku[web.1]: Process exited with status 1
2022-08-26T16:05:50.132264+00:00 heroku[web.1]: State changed from starting to crashed
```

my code: 

```
import mongoDB from "mongodb";
import connectToDatabase from "./config/dbConfig";
import * as actions from "./actions/botActions";
import { Context } from "telegraf";
import bot from "./config/botConfig";
import { telegrafThrottler } from "telegraf-throttler";

const throttler = telegrafThrottler();

const getClient = async (username: string | undefined) => {
  const db = await connectToDatabase();
  const clients: mongoDB.Collection = await db.collection("Clients");
  const client = await clients.findOne({ username: `${username}` });
  return client;
};

bot.command("test", async (ctx: Context) => {
  const client = await getClient(ctx.message?.from.username);
  ctx.reply(`Hello there ${client?.username}`);
});

bot.command("start", async (ctx: Context) => {
  const client = await getClient(ctx.message?.from.username);
  if (client) {
    bot.telegram.sendMessage(client.chatID, client.message, client.replyMarkup);
  }
});

bot.catch((e: Error) => console.log(" ~ * ~ * ~ BOT ERROR: ", e));
bot.use(actions);
bot.use(throttler);
bot.launch();
```

I am using typescript, mongoDB, telegram-throttler

**Comment by dr-iroh** [comment]
Please add the full error that heroku shows you. Since with that you can not know what is really happening

**Comment by MKRhere** [comment]
What he said ^ Need the full error. We see only the second half of the stack trace.

But also, a few observations:
* `bot.use(throttler)` should be moved up, before any other handlers, like your `bot.command`.
* All API calls (in fact, all async calls in your handlers) must be awaited. Here `await ctx.reply()`, `await bot.telegram.sendMessage()`, etc. Without this, Telegraf cannot catch your errors for `bot.catch()`.
* `bot.catch()` should not ignore all errors. This can leave Telegraf in an unstable state after a fatal error. You should normally handle known errors and rethrow unknown errors. It's better to let the bot crash and restart than be alive in a zombie state. Refer to: https://telegraf.js.org/#error-handling
