### ISSUE TITLE
Seems to stop listening after a few days

### ISSUE THREAD

**Issue by antony** [telegraf/telegraf#170]
Hi. Thanks for this library - it's excellent. Absolutely the best I've seen.

We have a bot running on zeit/now.sh, which listens for /commands in a channel.

it seems like every few days, the bot gets a few HTTP errors from Telegram's API, and stops listening.

The only way to get the bot to respond to commands again is to remove it from the channel and re-add it.

Is this a known issue?

These may not even be related, but it's all the logs contain:

```
09/03 04:03 AM (2d)
Failed to get updates. Waiting: 1s { Error: 500: Unsupported message from Telegram
    at buildPayload.then.then.then.then (/home/nowuser/src/node_modules/telegraf/lib/network/client.js:102:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.1</center>\r\n</body>\r\n</html>\r\n' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
09/03 04:03 AM (2d)
Failed to get updates. Waiting: 1s { Error: 500: Unsupported message from Telegram
    at buildPayload.then.then.then.then (/home/nowuser/src/node_modules/telegraf/lib/network/client.js:102:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.0</center>\r\n</body>\r\n</html>\r\n' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
09/03 04:03 AM (2d)
Failed to get updates. Waiting: 1s { Error: 500: Unsupported message from Telegram
    at buildPayload.then.then.then.then (/home/nowuser/src/node_modules/telegraf/lib/network/client.js:102:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.0</center>\r\n</body>\r\n</html>\r\n' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
09/03 04:03 AM (2d)
Failed to get updates. Waiting: 1s { Error: 500: Unsupported message from Telegram
    at buildPayload.then.then.then.then (/home/nowuser/src/node_modules/telegraf/lib/network/client.js:102:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.0</center>\r\n</body>\r\n</html>\r\n' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
```

**Comment by dotcypress** [comment]
Hey 👋 

Do you use LongPolling? If yes, you need to config your `now` instance to prevent freezing.
But my advice is using `Webhooks` for that.

**Comment by antony** [comment]
Ah - I hadn't considered webhooks. That does seem like a better idea. I'll try that! Thanks :)

**Comment by jjhesk** [comment]
same issue here

**Comment by dotcypress** [comment]
@jjhesk FYI Telegram down last 4 hours.

**Comment by antony** [comment]
@jjhesk the fix is listed above, you have to use webhooks.
