### ISSUE TITLE
Cannot read properties of undefined (reading 'sendMessage') in v4.11.2 but not in v3

### ISSUE THREAD

**Issue by suntong** [telegraf/telegraf#1793]
## Context

* Telegraf.js Version: v4.11.2
* Node.js Version: 18.x
* Operating System: Linux, in AWS Lambda (free layer)

## Minimal Example Code Reproducing the Issue

https://github.com/suntong/telegram-notify-bot-serverless/

If I upgrade telegraf to v4.11.2, by doing https://github.com/suntong/telegram-notify-bot-serverless/commit/928a0f9eacb6e643eb9372015f71a25d73227759
then I'll get the `Cannot read properties of undefined (reading 'sendMessage')` error.

Else, it works fine in v3. I.e, with commit:
https://github.com/suntong/telegram-notify-bot-serverless/commit/b6bf2db35605aa4eb3d83d362d73410902474ee4

## Error Message and Logs (`export DEBUG='telegraf:*'`)

```
2023-02-04T01:11:23.066Z telegraf:main Finished processing update 837769081
2023-02-04T01:11:23.067Z	55fb3081-c99f-4f6e-b0aa-d54a927695ea	INFO	Error:  TypeError: Cannot read properties of undefined (reading 'sendMessage')
    at reply (/var/task/node_modules/telegraf/lib/context.js:241:21)
    at sendLongMsg (/var/task/bot.js:27:9)
    at /var/task/bot.js:40:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (/var/task/node_modules/telegraf/lib/composer.js:474:17)
    at async /var/task/node_modules/telegraf/lib/composer.js:475:21
    at async execute (/var/task/node_modules/telegraf/lib/composer.js:474:17)
    at async /var/task/node_modules/telegraf/lib/composer.js:475:21
    at async execute (/var/task/node_modules/telegraf/lib/composer.js:474:17)
    at async /var/task/node_modules/telegraf/lib/composer.js:475:21
END RequestId: 55fb3081-c99f-4f6e-b0aa-d54a927695ea
```

**Comment by MKRhere** [comment]
In v3, context methods were bound, so you were able to do `myFunc(ctx.reply)`. Binding methods for each update is costly, so v4 no longer does this.

You should either bind the methods you want to pass: `myFunc(ctx.reply.bind(ctx))` or pass the ctx object and always call `ctx.reply()`.

Further reading about unbound and bound methods:
https://javascript.info/bind
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind

**Comment by MKRhere** [comment]
You may also want to check out v4 release notes:
https://github.com/telegraf/telegraf/releases/v4.0.0

**Comment by suntong** [comment]
Will take a look. thanks a lot for the swift reply.
