### ISSUE TITLE
Unable To Connect Telegram Server For Sending Messages Due To Errors Such As ERR_TLS_CERT_ALTNAME_INVALID and ECONNRESET

### ISSUE THREAD

**Issue by jerrychong25** [telegraf/telegraf#1816]
## Context
Hi all,

I'm trying to integrate Telegraf function with my Node.js app recently.

Unfortunately, it always failed to connect Telegram servers with few errors including ERR_TLS_CERT_ALTNAME_INVALID and ECONNRESET.

However, my laptop able to use Telegram apps and send/receive messages successfully.

Could anyone share solution on this?

* Telegraf.js Version: v4.12.1
* Node.js Version: v18.14.2
* Operating System: Ubuntu WSL2

Thanks in advance!

## Minimal Example Code Reproducing the Issue
```
const { Telegraf } = require('telegraf');
const bot = new Telegraf(config.TELEGRAM_BOT_TOKEN)
const chatId = config.TELEGRAM_CHAT_ID

bot.telegram.sendMessage(chatId, 
   `
   SIMPLE MESSAGE HERE
   `
);
```

## Expected Behavior
Able to connect Telegram server and send message successfully

## Current Behavior
Failed to connect Telegram server and unable to send message

## Error Message and Logs (`export DEBUG='telegraf:*'`)
Error Message 1:
```
.net, DNS:*.xz.fbcdn.net, DNS:facebook.com, DNS:messenger.com
    at ClientRequest.<anonymous> (/....../node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ERR_TLS_CERT_ALTNAME_INVALID',
  code: 'ERR_TLS_CERT_ALTNAME_INVALID'
}
```

Error Message 2:
```
/......../node_modules/node-fetch/lib/index.js:1505
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://api.telegram.org/bot6229251694:[REDACTED]/sendMessage failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/....../node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

**Comment by MKRhere** [comment]
Discussed in the chat; these are network related issues.

**Comment by jerrychong25** [comment]
Thank you @MKRhere !
