### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Object

### ISSUE THREAD

**Issue by victor-lkmx** [telegraf/telegraf#1858]
## Context

* Telegraf.js Version: 4.12.2
* Node.js Version:v16.17.0
* Operating System: MacOS

## Minimal Example Code Reproducing the Issue

I'm just putting an inline keyboard in a debug command.

```javascript
    ctx.reply('Scenes', Markup.keyboard([
        [Markup.button.text("Hi"), Markup.button.text("Hi"), Markup.button.text("Hi")]
    ]).resize()
);
```

When the bot is in a private chat, it displays the inline keyboard without problems, but when the bot is in a group chat an error is gotten from Telegram's API.

## Expected Behavior

To see the inline keyboard in my group chat.

## Current Behavior

An exception is thrown with this error

```

TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Object

```

## Error Message and Logs

```
telegraf:client HTTP call sendMessage {
  chat_id: -962100487,
  message_thread_id: undefined,
  reply_markup: { keyboard: [ [Array] ], resize_keyboard: true },
  text: 'Scenes'
} +9s
  telegraf:main Finished processing update 661874985 +91ms
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 661874986, allowed_updates: [] } +1ms
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Object
    at new NodeError (node:internal/errors:387:5)
    at new ClientRequest (node:_http_client:159:11)
    at request (node:https:357:10)
    at /Users/victor/xo/bots/hal/node_modules/node-fetch/lib/index.js:1482:15
    at new Promise (<anonymous>)
    at fetch (/Users/victor/xo/bots/hal/node_modules/node-fetch/lib/index.js:1451:9)
    at Telegram.callApi (/Users/victor/xo/bots/hal/node_modules/telegraf/lib/core/network/client.js:282:52) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by victor-lkmx** [comment]
My bad, it was a middleware messing around with the ctx

**Comment by victor-lkmx** [comment]
My bad, it was a middleware messing around with the ctx
