### ISSUE TITLE
not working even without any code   TelegramError: 404: Not Found

### ISSUE THREAD

**Issue by its-dibo** [telegraf/telegraf#1926]
```
 let bot = new Telegraf(token);

// no any other code, just launch the bot

bot.launch()
```

```
node_modules/telegraf/lib/core/network/client.js:302
            throw new error_1.default(data, { method, payload });
                  ^

TelegramError: 404: Not Found
    at Telegram.callApi (node_modules/telegraf/lib/core/network/client.js:302:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegraf.launch (node_modules/telegraf/lib/telegraf.js:182:78) {
  response: { ok: false, error_code: 404, description: 'Not Found' },
  on: { method: 'getMe', payload: {} }
}
```

Node.js v20.10.0

**Comment by uselessBoi21** [comment]
Hey , 
The issue seems to be with the modules pattern used in the specified location in the error.
location :[ node_modules/telegraf/lib/core/network/client.js]  uses commonjs module. 
I think it needs some fixing to adapt to the ES6 modules from commonjs module pattern
You will be getting the error if you are using the ES6 module ( i.e. import {Telegram} from 'telegraf') kind of import 
The commonjs module works fine with the require('telegraf') syntax

**Comment by MKRhere** [comment]
@uselessBoi21 The library is importable as ESM and CJS. That is not the issue. The server they're making a request to responds with 404. Which sounds to me like they're behind a bad proxy or their ISP is hijacking requests.

**Comment by its-dibo** [comment]
> The server they're making a request to responds with 404.

it is not the cause of the issue, because using telegram API directly or using other packages works well such as [node-telegram-bot-api](https://www.npmjs.com/package/node-telegram-bot-api)

**Comment by MKRhere** [comment]
>using telegram API directly

Directly how?

Are you using `HTTP_PROXY` env vars? I know that cURL and NTBA (via https://github.com/request/request) respect this, but Telegraf doesn't. With Telegraf, you should use [https-proxy-agent](https://www.npmjs.com/package/proxy-agent) and pass it as `new Telegraf(token, { telegram: { agent } })`.

**Comment by its-dibo** [comment]
> Are you using `HTTP_PROXY` env vars?

No, just a fresh Nodejs app

**Comment by MKRhere** [comment]
`HTTP_PROXY` is not set inside Node. Are you using a VPN service that sets this var, for example?
Anyhow, Telegraf is not able to reach Telegram Bot API, it seems. Can you try doing this?

```JS
fetch("https://api.telegram.org").then(res => res.text()).then(console.log)
```

**Comment by its-dibo** [comment]
> `HTTP_PROXY` is not set inside Node. Are you using a VPN service that sets this var, for example? Anyhow, Telegraf is not able to reach Telegram Bot API, it seems. Can you try doing this?
> 
> ```
> fetch("https://api.telegram.org").then(res => res.text()).then(console.log)
> ```

I don't use any proxy or VPN at all

**Comment by its-dibo** [comment]
> Telegraf is not able to reach Telegram Bot API, it seems. Can you try doing this?

yes

**Comment by MKRhere** [comment]
And? What's the result?

**Comment by jenyafomin** [comment]
Im facing the same issue but using a different library (grammyjs with Nestjs)

 
[Nest] 70016  - 01/08/2025, 1:22:56 PM   ERROR [ExceptionHandler] Call to 'getMe' failed! (404: Not Found)
GrammyError: Call to 'getMe' failed! (404: Not Found)
    at toGrammyError (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/grammy/out/core/error.js:47:12)
    at ApiClient.callApi (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/grammy/out/core/client.js:90:48)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at withRetries (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/grammy/out/bot.js:521:41)
    at Bot.init (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/grammy/out/bot.js:167:22)
    at InstanceWrapper.useFactory [as metatype] (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/services/back-end/src/notificator/telegram/telegram.module.ts:31:9)
    at Injector.instantiateClass (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/injector.js:369:37)
    at callback (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/injector.js:65:34)
    at Injector.resolveConstructorParams (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/injector.js:144:24)
    at Injector.loadInstance (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/injector.js:70:13)
    at Injector.loadProvider (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/injector.js:97:9)
    at /Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/instance-loader.js:56:13
    at async Promise.all (index 4)
    at InstanceLoader.createInstancesOfProviders (/Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/instance-loader.js:55:9)
    at /Users/mac16/Documents/IT/Apps/PROJETS/Cardex/crm-nest-telegram/node_modules/@nestjs/core/injector/instance-loader.js:40:13
    at async Promise.all (index 24)

**Comment by jenyafomin** [comment]
So in my case, I was passing wrong .env.BOT_TOKEN value and it happened because .env.BOT_TOKEN value is somehow set globally

To fix I clean the cached value:
```
unset BOT_TOKEN
```
