### ISSUE TITLE
Attach a webapp or url or image into answerInlineQuery doesn't work: BUTTON_TYPE_INVALID

### ISSUE THREAD

**Issue by chillbert** [telegraf/telegraf#1936]
Node verison: v20.10.0
telegraf: "^4.15.3"

I try to response (or make the user himself send a message) after the user calls the bot inline and makes a query and selects an article.
I assume to be able to send a webapp button (or url):

```
bot.on("inline_query", async (ctx) => {
  const results = [
    {
      type: "article",
      id: "1",
      title: "Book a Slot",
      input_message_content: {
        message_text: "Click on 'Open Web App' to book a slot!",
      },
    },
  ];

  try {
    await ctx.answerInlineQuery(results);
  } catch (error) {
    console.error("Error responding to inline query:", error);
  }
});

// This handler will be triggered when the user sends the selected inline query result to the chat.
bot.on("message", async (ctx) => {
  // Check if the message matches the one we expect
  if (ctx.message.text === "Book your slot:") {
    // Send a message with the Web App button
    await ctx.reply("Click the button below to open the Web App:", {
      reply_markup: {
        inline_keyboard: [
          [
            {
              text: "Open Web App", // The text of the button
              web_app: { url: "https://t.me/xxx/shortAppName" }, // The URL of your Web App
            },
          ],
        ],
      },
    });
  }
});

```

<img width="253" alt="image" src="https://github.com/telegraf/telegraf/assets/46078367/2c7af490-93a5-4080-951a-3ae45bfcff37">

no inline_keyboard button visible. 

same with this:
```

  const results = [
    {
      type: "article",
      id: "1",
      title: "Book a Slot",
      input_message_content: {
        message_text: "👉 Tap to book a slot via the Web App!",
      },
      reply_markup: {
        inline_keyboard: [
          [
            {
              text: "Book a Slot", // Button text
              web_app: { url: "https://t.me/xxx/shortAppName?id=32" }, // Your Web App URL
            },
          ],
        ],
      },
      // Optionally, if you have a URL you want to display directly in the message:
      url: "https://t.me/xxx/shortAppName?id=32",
      hide_url: true, // Set to true if you want to hide the URL in the message
      description: "Tap the button to book a slot via the Web App!",
      // You can also include a thumbnail image if you have one:
      thumbnail_url: "https://placekitten.com/100/100",
      thumbnail_width: 100,
      thumbnail_height: 100,
    },
    // ... other inline query results if needed ...
  ];
```

Or this:

```
bot.on('inline_query', async (ctx) => {
    const results = [
        {
            type: 'article',
            id: '1',
            title: 'Open Web App',
            input_message_content: {
                message_text: 'Click the button below to open the web app:'
            },
            reply_markup: {
                inline_keyboard: [
                    [{
                        text: 'Open Web App',
                        web_app: { url: 'https://t.me/xxx/shortAppName' }
                    }]
                ]
            }
        }
    ];

    try {
        await ctx.answerInlineQuery(results);
    } catch (error) {
        console.error('Error responding to inline query:', error);
    }
});
```

this gives me the following error:
```

Error responding to inline query: TelegramError: 400: Bad Request: BUTTON_TYPE_INVALID
    at Telegram.callApi (/home/runner/TONAdorableDarkseagreenMapping/node_modules/telegraf/lib/core/network/client.js:302:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/TONAdorableDarkseagreenMapping/index.js:31:5
    at async execute (/home/runner/TONAdorableDarkseagreenMapping/node_modules/telegraf/lib/composer.js:501:17)
    at async /home/runner/TONAdorableDarkseagreenMapping/node_modules/telegraf/lib/composer.js:502:21
    at async execute (/home/runner/TONAdorableDarkseagreenMapping/node_modules/telegraf/lib/composer.js:501:17)
    at async /home/runner/TONAdorableDarkseagreenMapping/node_modules/p-timeout/index.js:50:13 {
  response: {
    ok: false,
    error_code: 400,
    description: 'Bad Request: BUTTON_TYPE_INVALID'
  },
  on: {
    method: 'answerInlineQuery',
    payload: { inline_query_id: '114575293936607688', results: [Array] }
  }
}
```

**Comment by MKRhere** [comment]
The last two option looks fine. You have to use the real URL of your web app, and not the t.me URL.

**Comment by sashayudaev** [comment]
I'm facing the same problem. I'm trying to utilize the web_app parameter within inline_keyboard while processing an inline query but I do get an error mentioned here.

I'm sure the webapp url is fine because I've tried to use inline_keyboard in a bot response and it worked fine. But once I try to do the same in an inline query, the error pops up.

The [docs](https://core.telegram.org/bots/api#inlinekeyboardbutton) say "web_app" is limited to only private chats between a bot and a user

> The Web App will be able to send an arbitrary message on behalf of the user using the method [answerWebAppQuery](https://core.telegram.org/bots/api#answerwebappquery). Available only in private chats between a user and the bot. Not supported for messages sent on behalf of a Telegram Business account.

Replacing web_app with a regular url button markup works though

**Comment by hypernova7** [comment]
Short answer: You are trying to use a button that is only allowed to be used in private chats

Instead you can use a button url with the short webapp url to avoid exposing the real url, or use the AswerInlineQuery button parameter


```js
answerInlineQuery(results, {
  button: {
    text: 'Open webapp',
    web_app: {
      url: '...'
    }
  }
})
```
With that a link will appear at the beginning of the results list

**Comment by JerakRus** [comment]
Hello everyone. I am facing a similar problem, and I also realized that the problem is that I am trying to use web_app not in a private chat. Does telegram have plans to make the web_app parameter in all chats? My case is as follows: an entity (event) is created inside the mini app. Then, through an inline request, the user shares this event to chat (as article), and there should be a button for other users to open this event in the mini app. I don’t understand how to do it differently, it seems that the web_app parameter needs to be available in all chats.

**Comment by MKRhere** [comment]
> Does telegram have plans to make the web_app parameter in all chats?

We cannot answer that, and there's no such messaging from Telegram. So I would presume the answer is no.

Closing as resolved.
