### ISSUE TITLE
Getting ETIMEDOUT while running Telegraf bot in docker container with network mode host

### ISSUE THREAD

**Issue by ne0c0de** [telegraf/telegraf#1961]
* Telegraf.js Version: Final version
* Node.js Version: v21
* Operating System: Ubuntu:latest

## Minimal Example Code Reproducing the Issue

```js
const { Telegraf } = require('telegraf')
const bot = new Telegraf('TELEGRAM_TOKEN')

bot.telegram.setMyCommands([
    {command: 'start', description: 'Starts the system'},
    {command: 'restart', description: 'Restarts the system'},
    {command: 'help', description: 'Show commands help'},
])
bot.start((ctx) => {
    console.log(new Date(), 'started:', ctx.from)
    return ctx.reply('Hello Boss')
})

bot.launch()
```

```Dockerfile
FROM ubuntu:latest

WORKDIR /usr/src/app

RUN apt-get update && apt-get install curl build-essential libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libgtk-3-0 libxshmfence1 libgbm-dev openssl tesseract-ocr git libc++-dev chromium-browser -y

RUN curl -fsSL https://deb.nodesource.com/setup_21.x | bash -
RUN apt-get install -y nodejs

COPY package.json ./package.json

RUN npm install
RUN npm install pm2 -g

COPY . .

CMD ["pm2-runtime", "--error", "./log/err.log", "--output", "./log/out.log" , "index.js"]

```
If I run docker container with network mode on host, with this command:

```
docker run --privileged -itd --mount type=bind,source=/ctb/log,target=/usr/src/app/log --network host --name ttelegraf hardc0der/ttelegraf:latest
```

I'm getting this error instantly:

```
FetchError: request to https://api.telegram.org/bot6411340281:[REDACTED]/setMyCommands failed, reason:
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:492:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```
I'm getting 200 response to my request when I logged in to container and make a CURL request to api.telegram.org

If I remove ```--network host``` from the running command, everything is running smoothly

What can be the reason to get this error while running in host mode network?

**Comment by neko0xff** [comment]
I get the same problem when I run it on a physical machine.
```zsh=
# user @ Host-02 in ~/文件/GitHub/2023_schoolResearch_Server-HW/src/Server/mqtt_bot_node on git:main x [13:02:30] C:1
$ npm start

> mqtt_bot_node@1.0.0 start
> node index.js

[2024/3/3 下午1:03:10] Service is Starting.....
(node:111283) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

/home/user/文件/GitHub/2023_schoolResearch_Server-HW/src/Server/mqtt_bot_node/node_modules/node-fetch/lib/index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://api.telegram.org/bot7063183971:[REDACTED]/getMe failed, reason: 
    at ClientRequest.<anonymous> (/home/user/文件/GitHub/2023_schoolResearch_Server-HW/src/Server/mqtt_bot_node/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at TLSSocket.socketErrorListener (node:_http_client:492:9)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

Node.js v21.6.2

```
* My environment:
![圖片](https://github.com/telegraf/telegraf/assets/54382007/8082006a-e75e-4799-a6bd-808887f47889)
* My source code: https://github.com/neko0xff/2023_schoolResearch_Server-HW/tree/main/src/Server/mqtt_bot_node

**Comment by MKRhere** [comment]
It's likely your network itself that's blocking the request. Try over a VPN?

**Comment by ne0c0de** [comment]
> It's likely your network itself that's blocking the request. Try over a VPN?

As I mentioned on the issue, the problem is not related with network/firewall because I can able to send a GET request inside the docker machine, only telegraf bot getting this error when it's try to access to same URL

**Comment by MKRhere** [comment]
> while running in host mode network

I have no idea why this would affect it. Someone more experienced with Docker should try to help. I'd start by investigating whether it works outside the container, and does it consistently work without `--network host` (to rule out flaky network).

However @neko0xff's issue is very likely network blocking requests to Telegram domains.

**Comment by neko0xff** [comment]
I use curl & Postman test, is can work!
(I not use VPN)
![圖片](https://github.com/telegraf/telegraf/assets/54382007/29389503-4f45-46e6-b52a-197eca6e447b)

**Comment by ne0c0de** [comment]
> > while running in host mode network
> 
> I have no idea why this would affect it. Someone more experienced with Docker should try to help. I'd start by investigating whether it works outside the container, and does it consistently work without `--network host` (to rule out flaky network).
> 
> However @neko0xff's issue is very likely network blocking requests to Telegram domains.

docker without host network is working without any problem, also same code works on host machine without docker but when I put it in a docker container with configures as host network then it takes that error

**Comment by MKRhere** [comment]
I recently discovered that Node.js choosing IPv6 by default could be the root of this problem. If you still suffer from this issue, consider testing the following fix:

```TS
import { setDefaultResultOrder } from "node:dns";
setDefaultResultOrder("ipv4first");
```

Or if you use legacy require:

```TS
const { setDefaultResultOrder } = require("node:dns");
setDefaultResultOrder("ipv4first");
```

This has to be done *before* calling `bot.launch`.

**Comment by ne0c0de** [comment]
I will try this, thanl you so much

**Comment by MKRhere** [comment]
Did that solve this issue?

**Comment by impuLssse** [comment]
I have same error
Please tell me what could be the problem
<img width="1140" alt="image" src="https://github.com/telegraf/telegraf/assets/86838048/5f416ee3-8d1d-4026-9824-202b7d254beb">
<img width="788" alt="image" src="https://github.com/telegraf/telegraf/assets/86838048/bada3df7-b986-43c6-884d-6af1deb80805">

**Comment by impuLssse** [comment]
Network remote docker settings in dev container
<img width="1374" alt="image" src="https://github.com/telegraf/telegraf/assets/86838048/5fa0e497-dcbb-4acc-91ae-919a15f42343">

**Comment by dongitran** [comment]
I had a similar issue and fixed it by downgrading the node version to `node:16-alpine`

hopefully it will help you too.

**Comment by PororoManon** [comment]
> fixed it by downgrading the node version to node:16-alpine

this work on me, but I don't use docker. I use native NodeJS on machine. I got error on `node v20.12.2 LTS: Iron`. then I downgrade it to `node v16.20.2 (npm v8.19.4) LTS: gallium`

**Comment by jrandiny** [comment]
Downgrading to node 18 (in docker) also fix this issue for me. Compared to node 16, using node 18 is better because it still has security support

**Comment by HuluWZ** [comment]
I have same error  using telegraf with nodejs   v20.13.1 , docker  v26.1.2, Telegraf v4.16
it work after restart and crash after some delay i tried to use 
```
   import { setDefaultResultOrder } from "node:dns";
    setDefaultResultOrder("ipv4first");
```
it doesn't work here are sample screenshots
here is my code 

> _import { Markup, Telegraf } from "telegraf";
import { client } from "../libs/client";
import { InsertTelegramInfoDocument } from "~~/.gql/types";

const AUTHENTICATOR_BOT_TOKEN = process.env.AUTHENTICATOR_BOT_TOKEN!;

export async function initializeBot() {
  try {
    const bot = new Telegraf(AUTHENTICATOR_BOT_TOKEN);

    bot.on("contact", async (ctx) => {
      const telegramId = ctx.chat.id.toString();
      const { first_name, phone_number: phone_no } = ctx.message.contact;
      const { data } = await client.mutate({
        mutation: InsertTelegramInfoDocument,
        variables: {
          telegramId,
          phone_no,
          is_complete: !!phone_no,
        },
      });
      if (data?.insert_auth_telegram_info_one) {
        // const is_complete = data?.insert_auth_telegram_info_one.is_complete;
        // console.log({ is_complete });
        ctx.reply(`Thank you for sharing your contact  ${first_name} 👍`, Markup.removeKeyboard());
      } else {
        ctx.reply("Error Sharing Contact");
      }
    });

    bot.launch(() => console.log("Authenticator Bot started"));

    // Enable graceful stop
    process.once("SIGINT", () => bot.stop("SIGINT"));
    process.once("SIGTERM", () => bot.stop("SIGTERM"));
  } catch (err) {
    console.error("Error starting Authenticator Bot", err);
  }
}
_

![Screenshot from 2024-06-06 10-01-17](https://github.com/telegraf/telegraf/assets/59336998/34716577-03b3-40d4-be72-463b18860b6a)

![Screenshot from 2024-06-06 09-59-15](https://github.com/telegraf/telegraf/assets/59336998/49d32e7f-3d76-4a54-b3f4-e768265b336f)

**Comment by MKRhere** [comment]
https://github.com/telegraf/telegraf/issues/1981#issuecomment-2144059284

**Comment by tigermax139** [comment]
> I recently discovered that Node.js choosing IPv6 by default could be the root of this problem. If you still suffer from this issue, consider testing the following fix:
> 
> ```ts
> import { setDefaultResultOrder } from "node:dns";
> setDefaultResultOrder("ipv4first");
> ```
> 
> Or if you use legacy require:
> 
> ```ts
> const { setDefaultResultOrder } = require("node:dns");
> setDefaultResultOrder("ipv4first");
> ```
> 
> This has to be done _before_ calling `bot.launch`.

It works for me, thanks

**Comment by tarikhagustia** [comment]
got same issue using digitalocean app platform

**Comment by timurkayzer** [comment]
> got same issue using digitalocean app platform

Did you have any success solving it? Having the same problem now, downgrading version and using IP V4 didn't help.

**Comment by tarikhagustia** [comment]
> > got same issue using digitalocean app platform
> 
> Did you have any success solving it? Having the same problem now, downgrading version and using IP V4 didn't help.

I change the runtime from nodejs into bun it's working

**Comment by zerox2f** [comment]
> > got same issue using digitalocean app platform
> 
> Did you have any success solving it? Having the same problem now, downgrading version and using IP V4 didn't help.

try this:

```
import { setDefaultResultOrder } from "node:dns";
setDefaultResultOrder("ipv6first");
```

i'm using nodejs v22.10.0, it worked for me.

**Comment by psaruks** [comment]
Only downgrade to node:18 works for me...

**Comment by Russia9** [comment]
In my case (when running on high-ping network) the problem was really only in hardcoded timeout of 500ms in 
https://github.com/telegraf/telegraf/blob/0638cf4cc7ba8467ccb9222726024c99c54d119f/src/core/network/client.ts#L234

I think this value should be configurable.

**Comment by dodyagung** [comment]
Now is 2025 and this issue still occurs (node 22 lts)

I spent 2 days doing analysis on telegraf, **before realizing that it was actually a nodejs problem**

> I recently discovered that Node.js choosing IPv6 by default could be the root of this problem. If you still suffer from this issue, consider testing the following fix:
> 
> import { setDefaultResultOrder } from "node:dns";
> setDefaultResultOrder("ipv4first");
> Or if you use legacy require:
> 
> const { setDefaultResultOrder } = require("node:dns");
> setDefaultResultOrder("ipv4first");
> This has to be done _before_ calling `bot.launch`.

this solution didn't work for me

> Downgrading to node 18 (in docker) also fix this issue for me. Compared to node 16, using node 18 is better because it still has security support

and this is what worked!

**Comment by dodyagung** [comment]
> > > got same issue using digitalocean app platform
> > 
> > 
> > Did you have any success solving it? Having the same problem now, downgrading version and using IP V4 didn't help.
> 
> try this:
> 
> ```
> import { setDefaultResultOrder } from "node:dns";
> setDefaultResultOrder("ipv6first");
> ```
> 
> i'm using nodejs v22.10.0, it worked for me.

I thought this was a typo because the previous post was ipv4, but this is ipv6. I tried it, and it works!

https://github.com/dodyagung/telegram-sale-bot/commit/efbbfcdf94cf5c76735715dd9da08d14de486b2f

**Comment by eyobed-dev** [comment]
> > > > got same issue using digitalocean app platform
> > > 
> > > 
> > > Did you have any success solving it? Having the same problem now, downgrading version and using IP V4 didn't help.
> > 
> > 
> > try this:
> > ```
> > import { setDefaultResultOrder } from "node:dns";
> > setDefaultResultOrder("ipv6first");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i'm using nodejs v22.10.0, it worked for me.
> 
> I thought this was a typo because the previous post was ipv4, but this is ipv6. I tried it, and it works!
> 
> [dodyagung/telegram-sale-bot@efbbfcd](https://github.com/dodyagung/telegram-sale-bot/commit/efbbfcdf94cf5c76735715dd9da08d14de486b2f)

This is the solution

**Comment by MiltonA123** [comment]
Me funciono a mi degradando mi version de node js a la version 18.20.2 sin usar
// import { setDefaultResultOrder } from "node:dns";
// setDefaultResultOrder("ipv4first");

**Comment by Fatpandac** [comment]
It’s fine after I added the proxy agent config.

```ts
const { HttpsProxyAgent }= require('https-proxy-agent')
...
this.telegram = new Telegram(process.env.TELEGRAM_NOTIFIER_BOT_TOKEN, {
  agent: new HttpsProxyAgent(process.env.HTTPS_PROXY || process.env.HTTP_PROXY || null)
});
```
