### ISSUE TITLE
Unsupported message from Telegram

### ISSUE THREAD

**Issue by jackkum** [telegraf/telegraf#209]
Code:
```JavaScript
const Telegraf = require('telegraf');
var bot = new Telegraf(config.telegram.token);
bot.on('text', (ctx) => {
  return ctx.reply('hi');
});
bot.startPolling();
```

Result
```
Failed to get updates. Waiting: 1s { Error: 500: Unsupported message from Telegram
    at TelegramError (/home/jackkum/test/node_modules/telegraf/lib/network/error.js:3:5)
    at buildPayload.then.then.then.then (/home/jackkum/test/node_modules/telegraf/lib/network/client.js:102:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
Failed to get updates. Waiting: 1s { Error: 500: Unsupported message from Telegram
    at TelegramError (/home/jackkum/test/node_modules/telegraf/lib/network/error.js:3:5)
    at buildPayload.then.then.then.then (/home/jackkum/test/node_modules/telegraf/lib/network/client.js:102:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
```

What I'm doing wrong?

**Comment by dotcypress** [comment]
Seems like temporary Telegram issue. Nothing to worry about.

**Comment by danielsalles** [comment]
The problem persists some time already. Can you check if it's a telegram problem, or something specific in the telegraph?

ref: https://github.com/telegraf/telegraf/issues/405
