### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 52): Error: 403: Forbidden: bot was blocked by the user

### ISSUE THREAD

**Issue by paixaop** [telegraf/telegraf#227]
I'm getting a unhandled promise rejection error when a user blocks the bot and I try to send a message to it.
I have set the bot.catch()

    bot.catch((err) => {
        console.log('bot error: ', err);
    });

and have the following code sending out the messages, which works for users that have not blocked the bot

```
try {
    let s = await SPRs.getPendingSPRs(session.data);
    if (s) {
        s.forEach(spr => {
            SPRs.processSPR(session, spr)
                .then((pspr) => {
                    let reply_markup = Markup.inlineKeyboard(pspr.buttons).extra().reply_markup;
                    bot.telegram.sendMessage(
                        id,
                        pspr.message,
                        Object.assign({
                            parse_mode: 'Markdown',
                            reply_markup
                        }));
                })
                .catch((err) => {
                    console.log(err);
                });
        });
    }
} catch (err) {
    console.log(err.message);
}
```

and the catch() sections are not catching the error.

```
Exception has occurred: TelegramError
TelegramError: 403: Forbidden: bot was blocked by the user
    at buildPayload.then.then.then.then (/Users/.../bot/node_modules/telegraf/core/network/client.js:102:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Is there something wrong with the code? How do I catch a bot blocked by user exception?
Thanks for the great work!

**Comment by dotcypress** [comment]
Hi @paixaop 

You need to add `return`  before `bot.telegram.sendMessage` to continue promise chain:

```js
try {
    let s = await SPRs.getPendingSPRs(session.data);
    if (s) {
        s.forEach(spr => {
            SPRs.processSPR(session, spr)
                .then((pspr) => {
                    let reply_markup = Markup.inlineKeyboard(pspr.buttons).extra().reply_markup;
                    return bot.telegram.sendMessage(
                        id,
                        pspr.message,
                        Object.assign({
                            parse_mode: 'Markdown',
                            reply_markup
                        }));
                })
                .catch((err) => {
                    console.log(err);
                });
        });
    }
} catch (err) {
    console.log(err.message);
}
```
