### ISSUE TITLE
Problem reply with photo

### ISSUE THREAD

**Issue by makhmudov** [telegraf/telegraf#265]
Hello telegraf team.
I am trying reply photo, but always getting error... What is wrong with my code:
```javascript
var photo = __dirname+'/img/123.jpg';
console.log(photo);
return ctx.replyWithPhoto({ source: fs.createReadStream(photo)});
```

This is error what I got:
```javascript
{ Error: 500: Unsupported message from Telegram
    at TelegramError (/var/www/html/telebot/node_modules/telegraf/core/network/error.js:3:5)
    at buildPayload.then.then.then.then (/var/www/html/telebot/node_modules/telegraf/core/network/client.js:102:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 500,
  response: 
   { error_code: 500,
     description: 'Unsupported message from Telegram',
     response: '<html>\r\n<head><title>500 Internal Server Error</title></head>\r\n<body bgcolor="white">\r\n<center><h1>500 Internal Server Error</h1></center>\r\n<hr><center>nginx/1.12.2</center>\r\n</body>\r\n</html>\r\n' },
  description: 'Unsupported message from Telegram',
  parameters: {} }
```
Image path is correct. Required fs:
```javascript
const fs = require('fs')
```

**Comment by Piterden** [comment]
Try like this https://github.com/Piterden/syntax-highlighter-bot/blob/1.0/src/bot.mjs#L316-L320

**Comment by dotcypress** [comment]
@makhmudov `Unsupported message from Telegram` means that Telegram server fails on API call.
And you can see raw Telegram answer in error details: `500 Internal Server Error`

**Comment by makhmudov** [comment]
@dotcypress thank you for your answer. But I know it. Its not may fault. I am using only telegraf library code and I put local path to the image file. Its telegraf's official example:
```javascript
bot.command('stream', (ctx) => ctx.replyWithPhoto({ source: fs.createReadStream('/cats/cat2.jpeg') }))
```
I am just using this code.

**Comment by makhmudov** [comment]
@Piterden thank you for your answer but I want reply local photo.

**Comment by Piterden** [comment]
Had you tried `fs.readFileSync`, instead of stream?

**Comment by makhmudov** [comment]
@Piterden yep but same error((

**Comment by Piterden** [comment]
```js
const replyWithPhoto = (ctx, path) => {
  ctx.replyWithChatAction('upload_photo')
  return ctx.replyWithPhoto(
    { url: getFileURL(path) },
    Markup.removeKeyboard().extra()
  )
}```
Try this helper.
