### ISSUE TITLE
Fastify webhook edit message

### ISSUE THREAD

**Issue by TheNoim** [telegraf/telegraf#290]
If you use webhooks with fastify you can't edit messages.

```
Error: 400: Bad Request: message to edit not found
      at buildPayload.then.then.then.then (/opt/tsviewer/node_modules/telegraf/core/network/client.js:116:17)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Example:

```javascript
fastify.use(bot.webhookCallback(pathname));
bot.telegram.setWebhook(webhook);
```

```javascript
const chatID = ctx.message.chat.id;
const message = await ctx.replyWithMarkdown('***Processing request...***');
await bot.telegram.editMessageText(chatID, message.message_id, undefined, string, {parse_mode: 'HTML'});
```
Versions:
fastify: 0.36.0
telegraf: 3.17.2

**Comment by dotcypress** [comment]
@TheNoim actually this is not a bug, because first reply will be served via webhook response and we can't get new message info here:
```js
const message = await ctx.replyWithMarkdown('***Processing request...***');
console.log(message) // {webhook: true}
```

To disable `reply via webhook feature` you can use any of following solutions:
```js
// Using contructor
const bot = new Telegraf(token, { telegram: { webhookReply: false} })

// Or using bot property
bot.webhookReply = false
```
