### ISSUE TITLE
Error: 400: Bad Request: message text is empty

### ISSUE THREAD

**Issue by watchdots** [telegraf/telegraf#323]
I received this error when a text message send to bot:
```
{ Error: 400: Bad Request: message text is empty
    at buildFetchConfig.then.then.then.then (E:\calcous\node_modules\telegraf\core\network\client.js:130:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: message text is empty' },
  description: 'Bad Request: message text is empty',
  parameters: {},
  on:
   { method: 'sendMessage',
     payload: { chat_id: 277164073, text: undefined } } }

```
this error will throw in this function:
```
BOT.on('text',(ctx)=>{
    let result = publicExpression(ctx.message.text);
    return ctx.reply(result);
})

```

What is the problem and what is the solution to this problem?

**Comment by dotcypress** [comment]
Hey!

Could you add `console.log(result)` and figure out which text sendt to Telegram server

**Comment by watchdots** [comment]
```
Decimal {
  constructor:
   { [Function: Decimal]
     ROUND_UP: 0,
     ROUND_DOWN: 1,
     ROUND_CEIL: 2,
     ROUND_FLOOR: 3,
     ROUND_HALF_UP: 4,
     ROUND_HALF_DOWN: 5,
     ROUND_HALF_EVEN: 6,
     ROUND_HALF_CEIL: 7,
     ROUND_HALF_FLOOR: 8,
     EUCLID: 9,
     set: [Function: config],
     config: [Function: config],
     clone: [Function: clone],
     isDecimal: [Function: isDecimalInstance],
     abs: [Function: abs],
     acos: [Function: acos],
     acosh: [Function: acosh],
     add: [Function: add],
     asin: [Function: asin],
     asinh: [Function: asinh],
     atan: [Function: atan],
     atanh: [Function: atanh],
     atan2: [Function: atan2],
     cbrt: [Function: cbrt],
     ceil: [Function: ceil],
     cos: [Function: cos],
     cosh: [Function: cosh],
     div: [Function: div],
     exp: [Function: exp],
     floor: [Function: floor],
     hypot: [Function: hypot],
     ln: [Function: ln],
     log: [Function: log],
     log10: [Function: log10],
     log2: [Function: log2],
     max: [Function: max],
     min: [Function: min],
     mod: [Function: mod],
     mul: [Function: mul],
     pow: [Function: pow],
     random: [Function: random],
     round: [Function: round],
     sign: [Function: sign],
     sin: [Function: sin],
     sinh: [Function: sinh],
     sqrt: [Function: sqrt],
     sub: [Function: sub],
     tan: [Function: tan],
     tanh: [Function: tanh],
     trunc: [Function: trunc],
     precision: 32,
     rounding: 4,
     toExpNeg: -7,
     toExpPos: 21,
     maxE: 9000000000000000,
     minE: -9000000000000000,
     modulo: 1,
     crypto: false,
     fromJSON: [Function] },
  s: 1,
  e: 1,
  d: [ 11 ] }
```
this is result of eval() function in mathjs!

**Comment by dotcypress** [comment]
Try to coerce to string: `ctx.reply(result + '')`

**Comment by watchdots** [comment]
Hoy Moly!
fixed.
We should use the format() function, which converts that JSON to numbers.
Why does the Telegraph assume undefined equal to empty?

**Comment by dotcypress** [comment]
@watchdots I believe it's just error message.
