### ISSUE TITLE
Error when sending document (sendDocument)

### ISSUE THREAD

**Issue by Ugarz** [telegraf/telegraf#329]
Hello,
I'm currently facing an issue when I want to send a document.
I tried 3 technics sending a local file, and a hosted file, neither document is sent.

[Link to the Telegraf documentation](http://telegraf.js.org/#/?id=senddocument)

### Sending local file (relativePath - asbolutePath)
```js
bot.on('text', (ctx) => {
  const localFile = '../../public/assets/test.txt'
  return bot.telegram.sendDocument(process.env.CHAT_ID, request(localFile), [{disable_notification: true}]);
})
```

### Sending hosted local file
With a simple server made by expressjs.
```js
bot.on('text', (ctx) => {
  const localFile = 'http://localhost:3000/assets/test.txt'
  return bot.telegram.sendDocument(process.env.CHAT_ID, request(localFile), [{disable_notification: true}]);
})
```

### Sending random remote file
```js
bot.on('text', (ctx) => {
  const remoteFile = 'http://www.lehtml.com/download/js_doc.pdf'
  return bot.telegram.sendDocument(process.env.CHAT_ID, request(remoteFile), [{disable_notification: true}]);
})
```

I'm still getting this error
```
[nodemon] starting `node server.js`
App running on port 3000!

  Error: 400: Bad Request: wrong URL host
      at buildConfig.then.then.then.then (/path/to/project/node_modules/telegraf/core/network/client.js:232:17)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Failed to process updates. { Error: 400: Bad Request: wrong URL host
    at buildConfig.then.then.then.then (/path/to/project/node_modules/telegraf/core/network/client.js:232:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: wrong URL host' },
  description: 'Bad Request: wrong URL host',
  parameters: {},
  on:
   { method: 'sendDocument',
     payload: { '0': [Object], chat_id: '-112511335', document: [Object] } } }
```
Does anyone has an idea of what I'm doing wrong ?

**Comment by sergeysova** [comment]
`request()` returns `Promise`

but `sendDocument` accepts `string` as `url`

**Comment by sergeysova** [comment]
try

```js
bot.on('text', async (ctx) => {
  const remoteFile = 'http://www.lehtml.com/download/js_doc.pdf'
  return bot.telegram.sendDocument(process.env.CHAT_ID, await request(remoteFile), [{disable_notification: true}]);
})
```

**Comment by Ugarz** [comment]
Thank you for answering me this quick @sergeysova !
Unfortunately, this remain the same.
I also tried
```js
bot.on('text', async (ctx) => {
  const remoteFile = await request('http://www.lehtml.com/download/js_doc.pdf')
  return bot.telegram.sendDocument(process.env.CHAT_ID, remoteFile, [{disable_notification: true}]);
})
```
Nothing more..

**Comment by sergeysova** [comment]
Please, show terminal output of

```js
bot.on('text', (ctx) => {
  const remoteFile = 'http://www.lehtml.com/download/js_doc.pdf'

  return bot.telegram.sendDocument(process.env.CHAT_ID, remoteFile, [{ disable_notification: true }]);
})
```

**Comment by Ugarz** [comment]
Okay I finally managed to use it :)
In fact I did not needed to use `request` at all. You were right !
So the final code is :
```js
bot.on('text', (ctx) => {
  if(ctx.message && ctx.message.text === 'doc'){
    const remoteFile = 'http://www.lehtml.com/download/js_doc.pdf'
    return bot.telegram.sendDocument(process.env.CHAT_ID, remoteFile, [{disable_notification: true}]);
  }
  return;
})
```
If the text sent is `doc`, then send the document.
Thank you @sergeysova for your help !
