### ISSUE TITLE
Too many requests  error

### ISSUE THREAD

**Issue by Aka-San** [telegraf/telegraf#436]
## Context

* Telegraf.js Version: latest
* Node.js Version: 10.4.0
* Operating System: Windows 10 x64

## Expected Behavior

The bot must process all requests, even if there are too many

## Current Behavior

Bot crashes after trying to process too many requests. Even after restart, tries to process requests

## Failure Information (for bugs)

The bot has received too many requests, and trying to process them, it crashes.
### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. The bot was created, everything worked fine
2. Some people adding a bot with a supergroup and started spamming bot requests
3. Bot crashed and after reboot also tries to process those requests

### Failure Logs

```
(node:8660) UnhandledPromiseRejectionWarning: Error: 429: Too Many Requests: retry after 5
    at buildConfig.then.then.then.then (C:\Users\homek\Desktop\bot\node_modules\telegraf\core\network\client.js:235:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

And a lot of the same errors

**Comment by Aka-San** [comment]
lol, i just add bot.catch like this:
```
const bot = new Telegraf(TOKEN, {username: 'helpminebot'})
bot.catch((err) => {
  console.log('Ooops', err)
})
```
it just work
