### ISSUE TITLE
I am getting error from the server for delete function

### ISSUE THREAD

**Issue by athimannil** [telegraf/telegraf#499]
I have just created a bot in telegraf for deleting the contact and give a temporary message. Unfortunately there is some error while running it. 

```
bot.on('contact', preventContacts);

const preventContacts = async (ctx, next) => {
  const { from, contact } = ctx.message;
  // Delete contact
  await ctx.deleteMessage();
  // Give temporary message
  const { message_id } = await ctx.replyWithMarkdown(`Hi [${from.first_name||''} ${from.last_name||''}](tg://user?id=${from.id}) you put *${contact.first_name || ''} ${contact.last_name||''}*'s number which is not allowed in group please delete`);
  // Delete temporary message
  setTimeout(() => ctx.deleteMessage(message_id), 5 * 60 * 1000);
};
```

It seems to be the message deleted already and therefore getting error. Any one has clue how to fix it ? 

```
  Error: 400: Bad Request: message can't be deleted
      at buildConfig.then.then.then.then (/Users/mymac/Work/bots/what-to-eat/node_modules/telegraf/core/network/client.js:254:17)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)

Failed to process updates. { Error: 400: Bad Request: message can't be deleted
    at buildConfig.then.then.then.then (/Users/mymac/Work/bots/what-to-eat/node_modules/telegraf/core/network/client.js:254:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,                                                                                                          .json        yarn.lock
     description: 'Bad Request: message can\'t be deleted' },
  description: 'Bad Request: message can\'t be deleted',
  parameters: {},
  on:
   { method: 'deleteMessage',
     payload: { chat_id: 407853509, message_id: 567 } } }
```

**Comment by Piterden** [comment]
The bot can delete only its own messages in private chats.

**Comment by athimannil** [comment]
@Piterden Thanks a lot for your quick response 👍 
Add a condition to check whether it is private chat. Hope the javaScript code is okay other than adding condition ☺️

**Comment by Piterden** [comment]
NP, my friend.

If I remember right when the chat id equals with or contains (try both) your user id, then it is the private chat with you and the bot.

**Comment by athimannil** [comment]
@Piterden

**Comment by athimannil** [comment]
@Piterden what you think this solution 👇
```
const preventContacts = async (ctx, next) => {
  const { from, contact } = ctx.message;
  if (ctx.chat.type === 'private') return next();
  await ctx.deleteMessage();
```

**Comment by Piterden** [comment]
I think next would work correct only inside `,use()` methods, which called middlewares.

**Comment by athimannil** [comment]
Are there any option to know whether the bot has admin power or not before calling `ctx.deleteMessage();`

**Comment by athimannil** [comment]
@Piterden Finally I have found a solution to know where the bot can delete or not in the group 

`const deleteJoinMessage = await ctx.deleteMessage().then((response) => response, ({ response }) => response.ok)`

Please have a look and update you opinion

**Comment by Piterden** [comment]
```js
deleteMessage() {
  return new Promise((resolve) => {
    resolve(new Promise((resolve2) => {
      resolve2(deleteJoinMessage)
    }))
  })
}
```
