### ISSUE TITLE
Unable to send groups name in replyWithMarkdown

### ISSUE THREAD

**Issue by athimannil** [telegraf/telegraf#508]
Any  idea why not able to send group or channel name in `replyWithMarkdown`

```
const { message_id } = await ctx.replyWithMarkdown("Please join to our new group @javascript_dev")
```

**Comment by athimannil** [comment]
@Piterden getting error when the text contain `_` 

```
  Error: 400: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 223
      at buildConfig.then.then.then.then (/Users/Mo/Works/bots/what-to-eat/node_modules/telegraf/core/network/client.js:262:17)
      at <anonymous>      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Failed to process updates. { Error: 400: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 223
    at buildConfig.then.then.then.then (/Users/Mo/Works/bots/what-to-eat/node_modules/telegraf/core/network/client.js:262:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 400,
  response:
   { ok: false,
     error_code: 400,
     description: 'Bad Request: can\'t parse entities: Can\'t find end of the entity starting at byte offset 223' },
  description: 'Bad Request: can\'t parse entities: Can\'t find end of the entity starting at byte offset 223',
  parameters: {},  on:
   { method: 'sendMessage',     payload:
```

**Comment by Piterden** [comment]
What do you have on the offset 223? Try to escape it.

**Comment by athimannil** [comment]
@Piterden to be honest I didn't do any code which is about `offset`

**Comment by Piterden** [comment]
It is your right.

**Comment by athimannil** [comment]
@Piterden  Can I escape with `\_` this ?

**Comment by Piterden** [comment]
```
_You can try_
\_You can try_
```
_You can try_
\_You can try_

**Comment by Piterden** [comment]
The other way is to use `replyWithHtml`

**Comment by athimannil** [comment]
@Piterden The solution `\_` doesn't work

**Comment by Piterden** [comment]
Don't use replyWithMarkdown if you need _

**Comment by YouTwitFace** [comment]
Telegrams markdown doesn't support escaping.
