### ISSUE TITLE
Handle ECONNRESET

### ISSUE THREAD

**Issue by ajsb85** [telegraf/telegraf#57]
I can see many time this error.

```
Failed to get updates. { Error
    at ClientRequest.<anonymous> (C:\<path>\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'FetchError',
  message: 'request to https://api.telegram.org/bot<token>/getUpdates?offset=933321000&limit=100&timeout=30 failed, reason: read ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }
```

**Comment by ajsb85** [comment]
Hi @dotcypress 

This is the output when my bots are running.

```js
app.catch((err) => {
  console.log('Error', err)
})
```
I can see **ECONNRESET** and **ENOTFOUND** errors.
Don't worry I will perform a custom error-handling logic.

Thanks.
