### ISSUE TITLE
Answer Callback Query causing " Error: 400: Bad Request: URL_INVALID"

### ISSUE THREAD

**Issue by joshuaquek** [telegraf/telegraf#62]
I have tried running the code in the examples: https://github.com/telegraf/telegraf/blob/develop/examples/custom-router-bot.js

All of it works well (it is able to add and subtract), but once it hits the number 42, I get this error:

  Error: 400: Bad Request: URL_INVALID
      at TelegramError (/Users/joshuaquek/WebstormProjects/Tacts_Telegraf/node_modules/telegraf/lib/network/error.js:3:5)
      at buildPayload.then.then.then.then (/Users/joshuaquek/WebstormProjects/Tacts_Telegraf/node_modules/telegraf/lib/network/client.js:99:17)
      at process._tickCallback (internal/process/next_tick.js:103:7)

Failed to process updates. { Error: 400: Bad Request: URL_INVALID
    at TelegramError (/Users/joshuaquek/WebstormProjects/Tacts_Telegraf/node_modules/telegraf/lib/network/error.js:3:5)
    at buildPayload.then.then.then.then (/Users/joshuaquek/WebstormProjects/Tacts_Telegraf/node_modules/telegraf/lib/network/client.js:99:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 400,
  description: 'Bad Request: URL_INVALID',
  retryAfter: undefined,
  migrateToChaId: undefined }

Any workaround to this?

**Comment by dotcypress** [comment]
Hey.

Thank you for bug report. 👍 

It's just error in example with wrong usage of [`answerCallbackQuery`](http://telegraf.js.org/telegram.html#answercallbackquery)

Correct example:
```js
function editText (ctx) {
  return ctx.session.value !== 42
    ? ctx.editMessageText(`Value: <b>${ctx.session.value}</b>`, defaultMarkup).catch(() => undefined)
    : ctx.answerCallbackQuery('🎉', undefined, true).then(() => ctx.editMessageText(`🎉 ${ctx.session.value} 🎉`))
}
```

**Comment by joshuaquek** [comment]
Hi! yeah it works already, thank you!! :D
