### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by acerbisgianluca** [telegraf/telegraf#625]
## Context
* Telegraf.js Version: 3.27.1
* Node.js Version: 9.7.1
* Operating System: linux

## Expected Behavior
Bot should send a photo using a readable stream got using a package named request-stream which return (inside the callback) a readable stream of the http response which I pass to the source option.

## Current Behavior
Bot crashes when it reaches ctx.replyWithPhoto. If I uncomment the previous line, the bot works fine but 'msg' is not sent. People says it is related to webhook response, but I don't know.

### Steps to Reproduce
```
bot.command('/test', async (ctx) => {
	let url = await ig.find(); //it is jpg image url
	request(url, (err, res) => {
		if (err)
			return console.log(err);

		//ctx.reply('msg');
		ctx.replyWithPhoto({
			source: res
		});
	});
});
```

### Failure Logs
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at write_ (_http_outgoing.js:627:15)
    at ServerResponse.write (_http_outgoing.js:622:10)
    at MultipartStream.ondata (_stream_readable.js:651:20)
    at MultipartStream.emit (events.js:180:13)
    at MultipartStream.Readable.read (_stream_readable.js:487:10)
    at flow (_stream_readable.js:858:34)
    at resume_ (_stream_readable.js:840:3)
    at process._tickCallback (internal/process/next_tick.js:178:19)
Emitted 'error' event at:
    at ServerResponse.onerror (_stream_readable.js:675:12)
    at ServerResponse.emit (events.js:180:13)
    at ServerResponse.writeAfterEndNT (_http_outgoing.js:683:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by TiagoDanin** [comment]
Try using the await (`await request(...)`).
