### ISSUE TITLE
Deploy with Netlify Functions

### ISSUE THREAD

**Issue by weijinnx** [telegraf/telegraf#642]
## Context

* Telegraf.js Version: v3.28.0
* Node.js Version: v10.15.3
* Operating System: MacOS Mojave

## Expected Behavior

The build was successfully created.

## Current Behavior

Error: `ERROR in /Users/weijinnx/apps/twixen/node_modules/sandwich-stream/dist/sandwich-stream.mjs 32:29-37`

## Failure Information (for bugs)

I'm trying to deploy Telegraf bot with Netlify functions. But when I try to build the project with netlify-lambda - it fails.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Configure netlify
2. Add build command to package.json
3. Try to run it.

### Failure Logs

`ERROR in .../node_modules/sandwich-stream/dist/sandwich-stream.mjs 32:29-37`

**Comment by jh0ker** [comment]
I'm deploying directly with AWS Lambda via serverless, and I think I'm having the same issues. @weijinnx did you manage to fix it?

- Telegraf.js Version: v3.35.0
- Node.js Version: v12.14.1
- Operating System: Linux (Fedora)

I have some more logs that might provide more insight @dotcypress, it seems to be a problem with how the `sandwich-stream` library was built and/or my webpack config. I would appreciate any hints for how to fix it.

```
ERROR in ./node_modules/sandwich-stream/dist/sandwich-stream.mjs 32:29-37
Can't import the named export 'Readable' from non EcmaScript module (only default export is available)
 @ ./node_modules/telegraf/core/network/multipart-stream.js
 @ ./node_modules/telegraf/core/network/client.js
 @ ./node_modules/telegraf/telegram.js
 @ ./node_modules/telegraf/telegraf.js
 @ ./entrypoint/tg.js
 
  Error --------------------------------------------------
 
  Error: Webpack compilation error, see above
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/serverless-webpack/lib/compile.js:38:19
      at arrayEach (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/lodash/lodash.js:9342:14)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/serverless-webpack/lib/compile.js:31:11
      at tryCatcher (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:673:18)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/nodeback.js:42:21
      at finalCallback (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compiler.js:257:39)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compiler.js:273:13
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/Hook.js:154:20)
      at onCompiled (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compiler.js:271:21)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compiler.js:681:15
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/Hook.js:154:20)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compiler.js:678:31
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/Hook.js:154:20)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compilation.js:1423:35
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/Hook.js:154:20)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/webpack/lib/Compilation.js:1414:32
      at eval (eval at create (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/terser-webpack-plugin/dist/index.js:321:9
      at step (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/terser-webpack-plugin/dist/TaskRunner.js:111:15
      at tryCatcher (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/promise.js:673:18)
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/bluebird/js/release/nodeback.js:42:21
      at /home/jhoeke/git/p3nny/wdraktuell-bot-tg/node_modules/graceful-fs/graceful-fs.js:115:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

**Comment by jh0ker** [comment]
Update: I was able to compile successfully by adding this rule to my `webpack.config.js` under `module.rules`:

```js
{
    test: /\.mjs$/,
    type: 'javascript/auto',
},
```

**Comment by matias-kovero** [comment]
- Telegraf Version: 3.38.0
- Node Version: v12.18.3
- Operating System: MacOS Catalina


I'm currently trying to build a project using Telegraf typescript and netlify-lambda.

I'm getting:
```
$ netlify-lambda build dist
netlify-lambda: Building functions
[
  ModuleDependencyError: Can't import the named export 'Readable' from non EcmaScript module (only default export is available)
      at Compilation.reportDependencyErrorsAndWarnings (./node_modules/webpack/lib/Compilation.js:1468:21)
      at ./node_modules/webpack/lib/Compilation.js:1258:10
      at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
      at AsyncSeriesHook.lazyCompileHook (./node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.finish (./node_modules/webpack/lib/Compilation.js:1253:28)
      at ./node_modules/webpack/lib/Compiler.js:672:17
      at eval (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
      at ./node_modules/webpack/lib/Compilation.js:1185:12
      at ./node_modules/webpack/lib/Compilation.js:1097:9
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
      at HarmonyImportSpecifierDependency._getErrors (./node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:88:6)
      at HarmonyImportSpecifierDependency.getErrors (./node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
      at Compilation.reportDependencyErrorsAndWarnings (./node_modules/webpack/lib/Compilation.js:1463:22)
      at ./node_modules/webpack/lib/Compilation.js:1258:10
      at AsyncSeriesHook.eval [as callAsync] (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
      at AsyncSeriesHook.lazyCompileHook (./node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.finish (./node_modules/webpack/lib/Compilation.js:1253:28)
      at ./node_modules/webpack/lib/Compiler.js:672:17
      at eval (eval at create (./node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
      at ./node_modules/webpack/lib/Compilation.js:1185:12
      at ./node_modules/webpack/lib/Compilation.js:1097:9
      at processTicksAndRejections (internal/process/task_queues.js:79:11)
]
```
First I tried to add "@babel/preset-env", "@babel/preset-typescript" to help netlify-lambda understand that I'm using .ts files. It didn't work, it gave the same error. Then used `tsc` to compile my .ts to `/dist` and using netlify-lambda on the `/dist` file to handle only .js files. Still giving the same error.

Creating a rather simple file to reproduce this is to have a .ts and import Telegraf.

__src/bot.ts__
```js
import { Telegraf } from 'telegraf'; // If you remove this, it won't fire the error and netlify-lambda will success.

export async function handler(event, context) {
  return { statusCode: 200, body: '' };
}
```
`tsc` outDir -> /dist

`netlify-lambda build dist` Gives the error
