### ISSUE TITLE
How to handle albums or group of photos. 

### ISSUE THREAD

**Issue by nekorytaylor666** [telegraf/telegraf#777]
## Context

I'm using this handler to save file_ids of photos in scene session, then i send it as a media group to user.
`
mediaHandler.on('photo', ctx => {
  if (!ctx.scene.session.files) {
    ctx.scene.session.files = [];
  }
  ctx.scene.session.files.push({
    media: ctx.message.photo[1].file_id,
    type: 'photo',
  });
  ctx.reply(
    'message',
    Markup.keyboard([['Подтвердить'], ['Отмена']])
      .oneTime()
      .resize()
      .extra(),
  );
});
` 

* Telegraf.js Version: 3.32.0
* Node.js Version: v12.2.0
* Operating System: win10

## Expected Behavior

When i send mupliple photos as a separate photos i expected that i could handle them one by one. 

## Current Behavior

When i send photos as an album or separate photos Composer throw error
`TypeError: unwrap(...) is not a function
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\scenes\wizard\index.js:45:39
    at execute (C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:352:13)
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:352:49
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:120:56
    at execute (C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:352:13)
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:352:49
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\scenes\wizard\index.js:37:16
    at execute (C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:352:13)
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:337:14
    at C:\Users\Тохтар\Desktop\code\intrade_tg_bot\node_modules\telegraf\composer.js:128:56
    at processTicksAndRejections (internal/process/task_queues.js:89:5)`

**Comment by nekorytaylor666** [comment]
Oh, sorry had a typo in module.exports. I wrote module.export. It works fine)
