### ISSUE TITLE
Bot crashed with TypeError: Composer.unwrap(...) is not a function

### ISSUE THREAD

**Issue by ShiSHcat** [telegraf/telegraf#815]
I was running my telegram bot and it crashed with the error
```
TypeError: Composer.unwrap(...) is not a function
      at Promise.resolve.then (/root/kifilesgram/node_modules/telegraf/composer.js:129:56)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)

Failed to process updates. TypeError: Composer.unwrap(...) is not a function
    at Promise.resolve.then (/root/kifilesgram/node_modules/telegraf/composer.js:129:56)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
``` 
I cannot restart it.
Please help me fixing this issue. Bot code [here.](https://github.com/ShiSHcat/kifilesgram)

**Comment by Piterden** [comment]
Try to launch one of examples in docs

**Comment by ShiSHcat** [comment]
im  just dumb , i used  bot.command on undefined
