### ISSUE TITLE
unexpected token in nodejs 5.9.1

### ISSUE THREAD

**Issue by kepeto** [telegraf/telegraf#90]
hi, 

for some reason i cannot upgrade my nodejs from **5.9.1** to latest version (using windows server2003)

how to resolve this error?

(trying to use 'use strict' but it doesn't help)

```
d:\projects\node_modules\telegraf\lib\telegraf.js:8
class Telegraf extends Composer {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup
ported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

thanks

**Comment by dotcypress** [comment]
@kepeto Telegraf exclusively supports Node 6.2+
