### ISSUE TITLE
telegram.sendCopy don't work with media group

### ISSUE THREAD

**Issue by thantez** [telegraf/telegraf#911]
## Context and Current Behavior

Hi. I tried to use telegram.sendCopy function in my project but I saw when I send a media group to bot, it will send a copy of first picture at media group and then telegraf throws an error. I tried test this function by Telegraf examples, so run `echo-bot.js` and send media group to it and it have same behavior!

* Telegraf.js Version:
3.36.0
* Node.js Version:
13.7.0
* Operating System:
x86_64 Linux 5.4.15-2-MANJARO (Manjaro 18.1.5 Juhraya)

## Expected Behavior

when I try send a media group to bot and I use `(ctx.)telegram.sendCopy()`, it send a copy of media group (in one message) without error/exception and `echo-bot example` works for all message types.

### Failure Logs

```logs
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 1)


  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 2)


  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 3)


  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 4)


  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 5)


  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 6)


  TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
      at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
      at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
      at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
      at /home/thantez/temp/echo-bot/echo-bot.js:14:41
      at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Promise.all (index 7)

Failed to process updates. TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at formatHTML (/home/thantez/temp/echo-bot/node_modules/telegraf/markup.js:167:19)
    at Object.photo (/home/thantez/temp/echo-bot/node_modules/telegraf/core/replicators.js:110:16)
    at Telegram.sendCopy (/home/thantez/temp/echo-bot/node_modules/telegraf/telegram.js:410:27)
    at /home/thantez/temp/echo-bot/echo-bot.js:14:41
    at /home/thantez/temp/echo-bot/node_modules/telegraf/composer.js:143:56
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 1)
```

**Comment by mortezae** [comment]
@dotcypress I see the same error when sendCopy any media without caption.

**Comment by wojpawlik** [comment]
`sendCopy` is deprecated (hence `wontfix`) in favor of `copyMessage`, which also doesn't support media groups (hence `api limitations`)
