### ISSUE TITLE
Error: Cannot push to both `now` and `Heroku`

### ISSUE THREAD

**Issue by dalisoft** [telegraf/telegraf#94]
On node.js console shows these errors, please help me.
```sh
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
```

**Comment by dalisoft** [comment]
## `index.js`
```javascript
const Telegraf = require('telegraf');

const BOT_TOKEN = '366653326:XXXfHfT7RcbBZFphocUcZ1TZRa7_CXX-AXX';

const app = new Telegraf(BOT_TOKEN)

app.command('start', (ctx) => {
  console.log('start', ctx.from)
  ctx.reply('Welcome!')
})

app.hears('hi', (ctx) => ctx.reply('Hey there!'))

app.on('sticker', (ctx) => ctx.reply('??'))

app.startPolling()
```

## `package.json`
```javascript
{
  "name": "dalisoft_bot",
  "version": "1.0.0",
  "description": "Get expierence without skills",
  "main": "index.js",
  "scripts": {
    "start": "micro-bot -d MY_URL",
	"bot": "micro-bot -t MY_TOKEN index.js",
	"setconf": "heroku config:set --app botdstg BOT_TOKEN=MY_TOKEN",
	"bot_adv": "micro-bot -t MY_TOKEN -d MY_URL index.js",
	"commit": "git add index.js package.json && git commit -m \"Update\" && git push heroku master",
	"publish": "npm run commit && npm run bot",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "GPL-3.0",
  "dependencies": {
    "micro-bot": "^1.2.0",
    "telegraf": "^3.6.7"
  }
}
```

**Comment by dotcypress** [comment]
Hey.

You need to provide webhook domain for [now](https://github.com/telegraf/micro-bot#deployment-to-now) or [Heroku](https://github.com/telegraf/micro-bot#deployment-to-heroku) deploys.

**Comment by dalisoft** [comment]
But i am want use telegram api

**Comment by dalisoft** [comment]
I am provided webhook by telegram setwebhook param. But fail. Can you help me with docs or full guides. Free way would be best. Mu code anyway would be public on girhub

**Comment by dalisoft** [comment]
For now i cant set webhook due of random domain name on every publish

**Comment by dalisoft** [comment]
But i want use telegraf api. Sorry for much comments as i am with phone

**Comment by dalisoft** [comment]
@dotcypress I am changed `index.js` to [code you commented](https://github.com/telegraf/telegraf/issues/94#issuecomment-294379493), but will fail with 
```bash
......
  retryAfter: undefined,
  migrateToChatId: undefined }
Failed to get updates. Waiting: 1s { Error: 409: Conflict: can't use getUpdates
method while webhook is active
    at buildPayload.then.then.then.then (D:\GitHub\Telegram\bots\node_modules\te
legraf\lib\network\client.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 409,
  description: 'Conflict: can\'t use getUpdates method while webhook is active',

  retryAfter: undefined,
  migrateToChatId: undefined }
...
```

What i can do for make it working? It worked once or 2 times then fail these error.

Tried
* Reset webhook
* Remake project
* Revoke and Get new token

but failed

**Comment by dotcypress** [comment]
Hey. Could you provide full sources?

**Comment by dalisoft** [comment]
## index.js
```javascript
const { Composer } = require('micro-bot');
const app = new Composer()
app.command('start', (ctx) => {
  console.log('start', ctx.from)
  ctx.reply('Welcome!')
})
app.hears('hi', (ctx) => ctx.reply('Hey there!'))
app.on('sticker', (ctx) => ctx.reply('??'))
module.exports = app
```

## package.json
```javascript
{
  "name": "dalisoft_bot",
  "version": "1.0.0",
  "description": "Get expierence without skills",
  "main": "index.js",
  "scripts": {
    "start": "micro-bot -t 366653326:AAHfHfT7RcbBZFphocUcZ1TZRa7_C8R-A88 -d https://botdstg.herokuapp.com index.js",
	"bot": "micro-bot -t 366653326:AAHfHfT7RcbBZFphocUcZ1TZRa7_C8R-A88 index.js",
	"setconf": "heroku config:set --app botdstg BOT_TOKEN=366653326:AAHfHfT7RcbBZFphocUcZ1TZRa7_C8R-A88",
	"commit": "git add index.js package.json && git commit -m \"Update\" && git push heroku master",
	"publish": "npm run commit && npm run start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "GPL-3.0",
  "dependencies": {
    "micro-bot": "^1.2.0",
    "telegraf": "^3.6.7"
  }
}
```

**Comment by dalisoft** [comment]
Now erros gone, but not working yet

**Comment by dalisoft** [comment]
@dotcypress Do you see the code and/or Telegram bot?

**Comment by dalisoft** [comment]
Thanks for app/product. I think i am wasted full week for bot shit with nodejs for easy&flexiblity. I now sure,  i should move to `PHP` API.
