### ISSUE TITLE
replyWithPhoto error

### ISSUE THREAD

**Issue by shazgames** [telegraf/telegraf#961]
```javascript
ctx.replyWithPhoto({ url: 'https://picsum.photos/200/300/?random' })
```
throwing
```
_http_outgoing.js:780
    this.socket._writableState.corked = 1;
                                      ^

TypeError: Cannot set property 'corked' of undefined
    at ClientRequest.end (_http_outgoing.js:780:39)
    at MultipartStream.onend (_stream_readable.js:679:10)
    at Object.onceWrapper (events.js:417:28)
    at MultipartStream.emit (events.js:311:20)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Hamper** [comment]
Use just `ctx.replyWithPhoto('https://picsum.photos/200/300/?random')`

**Comment by LetItCode** [comment]
Its valid param too

`{ url: 'https://picsum.photos/200/300/?random' }`

I have not any errors

```
const Telegraf = require('telegraf')

const bot = new Telegraf(process.env.BOT_TOKEN)

const url = 'https://picsum.photos/200/300/?random'
bot.command('img', ctx => ctx.replyWithPhoto({ url }))

bot.launch()
```

**Comment by KnorpelSenf** [comment]
Closing because of inactivity.
